using System.Collections.Generic;
using UnityEngine;

namespace LearnAWS.Content
{
    /// <summary>
    /// Authors the Solutions Architect course in code. This is the single seam where, later, content can be
    /// loaded from ScriptableObjects/JSON instead — callers only ever see <see cref="CourseSpec"/>.
    /// Every block carries both an architecture position and a story ("town") position so the world can
    /// switch between the technical drawing and the narrative build.
    /// </summary>
    public static class SolutionsArchitectContent
    {
        public static CourseSpec BuildCourse()
        {
            return new CourseSpec
            {
                id = "saa-c03",
                title = "AWS Solutions Architect",
                topics = new List<TopicSpec> { BuildHighlyAvailableWebApp() }
            };
        }

        private static List<string> Ids(params string[] s) => new List<string>(s);

        private static TopicSpec BuildHighlyAvailableWebApp()
        {
            var t = new TopicSpec
            {
                id = "ha-web-app",
                title = "Build a Highly Available Web App",
                examDomain = "Design Resilient Architectures",
                summary = "Run a shop that survives a crowd, a broken worker, and a whole neighbourhood losing power."
            };

            // ---------- Containers (Architecture: wireframe plots. Story: the town's land/neighbourhoods.) ----------
            t.blocks.Add(new BlockSpec { id = "region", kind = AwsBlockKind.Region, displayName = "Region (eu-west-1)", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.4f, 0), size = new Vector3(14f, 3.2f, 10f), storyPosition = new Vector3(0, 0.7f, -2f), storyName = "The town", plainSummary = "The ground you build on — a geographic area such as eu-west-1.", realSummary = "Region eu-west-1 (Ireland). Contains multiple isolated Availability Zones." });
            t.blocks.Add(new BlockSpec { id = "azA", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), storyPosition = new Vector3(-3.4f, 0.7f, 1f), storyName = "Neighbourhood A", plainSummary = "An isolated tile of the region with its own power and network.", realSummary = "Availability Zone eu-west-1a." });
            t.blocks.Add(new BlockSpec { id = "azB", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), storyPosition = new Vector3(3.4f, 0.7f, 1f), storyName = "Neighbourhood B", plainSummary = "A second isolated tile, so one can fail and you stay up.", realSummary = "Availability Zone eu-west-1b." });
            t.blocks.Add(new BlockSpec { id = "vpc", kind = AwsBlockKind.Vpc, displayName = "VPC", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.1f, 0.3f), size = new Vector3(12.6f, 2.4f, 8.2f), storyPosition = new Vector3(0, 0.7f, 0f), storyName = "The plot", cidr = new CidrInfo("10.0.0.0", 16), arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "vpc/vpc-0a1b2c3d"), plainSummary = "Your walled private plot of land inside the region.", realSummary = "VPC 10.0.0.0/16 — 65,536 private addresses to carve into subnets." });
            t.blocks.Add(new BlockSpec { id = "pubA", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), storyPosition = new Vector3(-3.2f, 0.7f, -3.5f), storyName = "Front area A", cidr = new CidrInfo("10.0.0.0", 24), plainSummary = "A fenced area with a gate to the public road.", realSummary = "Public subnet 10.0.0.0/24 (eu-west-1a). Route table sends 0.0.0.0/0 to the internet gateway." });
            t.blocks.Add(new BlockSpec { id = "pubB", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), storyPosition = new Vector3(3.2f, 0.7f, -3.5f), storyName = "Front area B", cidr = new CidrInfo("10.0.1.0", 24), plainSummary = "The matching public area in the second neighbourhood.", realSummary = "Public subnet 10.0.1.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "privA", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), storyPosition = new Vector3(-3.4f, 0.7f, 2f), storyName = "Back area A", cidr = new CidrInfo("10.0.2.0", 24), plainSummary = "A fenced back area with no gate from the public road.", realSummary = "Private subnet 10.0.2.0/24 (eu-west-1a)." });
            t.blocks.Add(new BlockSpec { id = "privB", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), storyPosition = new Vector3(3.4f, 0.7f, 2f), storyName = "Back area B", cidr = new CidrInfo("10.0.3.0", 24), plainSummary = "The matching private area in the second neighbourhood.", realSummary = "Private subnet 10.0.3.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "asg", kind = AwsBlockKind.AutoScalingGroup, displayName = "Auto Scaling group", category = ServiceCategory.Compute, isContainer = true, position = new Vector3(0, 0.7f, 2.0f), size = new Vector3(12.6f, 1.5f, 3.8f), storyPosition = new Vector3(0, 0.7f, 1f), storyName = "The hiring crew", plainSummary = "A flexible boundary that hires or lets go of workers to match demand.", realSummary = "Auto Scaling group spanning both private subnets; min/desired/max instances scale on a metric." });

            // ---------- Service blocks ----------
            t.blocks.Add(new BlockSpec { id = "user", kind = AwsBlockKind.User, displayName = "Global user", category = ServiceCategory.Generic, position = new Vector3(0, 3.3f, -8.6f), storyPosition = new Vector3(0, 0.7f, -9.5f), storyName = "Visitor", plainSummary = "A person opening your app from somewhere in the world.", realSummary = "Client HTTPS request to your domain." });
            t.blocks.Add(new BlockSpec { id = "singleServer", kind = AwsBlockKind.GenericServer, displayName = "The one server", category = ServiceCategory.Compute, position = new Vector3(0, 0.7f, -1.2f), storyPosition = new Vector3(0, 0.7f, -4f), storyName = "The one shop", plainSummary = "One shop with one clerk doing everything. Fine — until a crowd arrives or it breaks.", realSummary = "A single public EC2 instance. No redundancy: a single point of failure." });
            t.blocks.Add(new BlockSpec { id = "igw", kind = AwsBlockKind.InternetGateway, displayName = "Internet gateway", category = ServiceCategory.Networking, position = new Vector3(0, 1.9f, -4.6f), storyPosition = new Vector3(0, 0.7f, -7.8f), storyName = "Road to the outside", plainSummary = "The one road between your plot and the public world.", realSummary = "Internet gateway attached to the VPC; only public subnets route to it." });
            t.blocks.Add(new BlockSpec { id = "alb", kind = AwsBlockKind.ApplicationLoadBalancer, displayName = "Application Load Balancer", category = ServiceCategory.Networking, position = new Vector3(0, 1.2f, -1.6f), storyPosition = new Vector3(0, 0.7f, -4f), storyName = "Front desk", endpoint = "app-alb-123.eu-west-1.elb.amazonaws.com", ports = new[] { "80", "443" }, arn = new ArnInfo("elasticloadbalancing", "eu-west-1", "123456789012", "loadbalancer/app/app-alb/50dc"), plainSummary = "The front desk: greets every visitor and sends them to a free, healthy worker.", realSummary = "Internet-facing ALB across both public subnets; health-checks targets and drops unhealthy ones." });
            t.blocks.Add(new BlockSpec { id = "ec2A", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A", category = ServiceCategory.Compute, position = new Vector3(-3.8f, 0.7f, 1.7f), storyPosition = new Vector3(-3.2f, 0.7f, -0.5f), storyName = "Worker A", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa1"), plainSummary = "A worker doing the real work — kept out back, away from the street.", realSummary = "EC2 in private subnet A; only the ALB's security group may reach port 80." });
            t.blocks.Add(new BlockSpec { id = "ec2A2", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A2 (scaled out)", category = ServiceCategory.Compute, position = new Vector3(-2.4f, 0.7f, 2.7f), storyPosition = new Vector3(-4.6f, 0.7f, 0.8f), storyName = "Extra worker", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa2"), plainSummary = "An extra worker hired automatically when the queue grew.", realSummary = "EC2 added by the Auto Scaling group during a scale-out event." });
            t.blocks.Add(new BlockSpec { id = "ec2B", kind = AwsBlockKind.Ec2Instance, displayName = "Web server B", category = ServiceCategory.Compute, position = new Vector3(3.8f, 0.7f, 1.7f), storyPosition = new Vector3(3.2f, 0.7f, -0.5f), storyName = "Worker B", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0bb1"), plainSummary = "A worker in the other neighbourhood, so losing one neighbourhood doesn't stop work.", realSummary = "EC2 in private subnet B." });
            t.blocks.Add(new BlockSpec { id = "rdsPrimary", kind = AwsBlockKind.RdsPrimary, displayName = "RDS primary", category = ServiceCategory.Database, position = new Vector3(-3.5f, 0.7f, 3.5f), storyPosition = new Vector3(-3.2f, 0.7f, 2.8f), storyName = "Records office", endpoint = "app-db.abc.eu-west-1.rds.amazonaws.com:5432", arn = new ArnInfo("rds", "eu-west-1", "123456789012", "db:app-db"), plainSummary = "The records office — the shared source of truth all workers rely on.", realSummary = "RDS primary (Multi-AZ) in eu-west-1a with a synchronous standby in 1b." });
            t.blocks.Add(new BlockSpec { id = "rdsStandby", kind = AwsBlockKind.RdsStandby, displayName = "RDS standby", category = ServiceCategory.Database, position = new Vector3(3.5f, 0.7f, 3.5f), storyPosition = new Vector3(3.2f, 0.7f, 2.8f), storyName = "Backup records", plainSummary = "A live copy of the records, ready to take over the instant the main office goes dark.", realSummary = "RDS standby in eu-west-1b; promoted automatically on failover." });
            t.blocks.Add(new BlockSpec { id = "cloudfront", kind = AwsBlockKind.CloudFront, displayName = "CloudFront", category = ServiceCategory.Edge, position = new Vector3(2.4f, 3.0f, -6.9f), storyPosition = new Vector3(2.2f, 0.7f, -7f), storyName = "Pickup point", endpoint = "d111abcdef.cloudfront.net", plainSummary = "A local pickup point that keeps copies near each visitor for speed.", realSummary = "CloudFront distribution; origin = the ALB." });
            t.blocks.Add(new BlockSpec { id = "route53", kind = AwsBlockKind.Route53, displayName = "Route 53", category = ServiceCategory.Edge, position = new Vector3(-2.4f, 3.0f, -6.9f), storyPosition = new Vector3(-2.2f, 0.7f, -7f), storyName = "Signpost", plainSummary = "The signpost that turns your name into directions to the right place.", realSummary = "Route 53 hosted zone; alias record app.example.com -> CloudFront." });

            // ---------- Connections (with the three-questions requirement detail) ----------
            t.connections.Add(new ConnectionSpec { id = "c_user_server", fromBlockId = "user", toBlockId = "singleServer", flow = ConnectionFlowKind.Request, plainSummary = "The visitor walks straight up to the one shop.", requirement = new ConnectionRequirement { addressNote = "the shop's public IP", permissionNote = "security group allows 80 from anywhere", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "0.0.0.0/0"), routeNote = "public, reachable from the street" } });
            t.connections.Add(new ConnectionSpec { id = "c_user_r53", fromBlockId = "user", toBlockId = "route53", flow = ConnectionFlowKind.Request, plainSummary = "Where is it? The visitor asks the signpost for directions.", requirement = new ConnectionRequirement { addressNote = "your name app.example.com", permissionNote = "public, no permission needed", routeNote = "public internet" } });
            t.connections.Add(new ConnectionSpec { id = "c_r53_cf", fromBlockId = "route53", toBlockId = "cloudfront", flow = ConnectionFlowKind.Request, plainSummary = "The signpost points to the nearest pickup point.", requirement = new ConnectionRequirement { addressNote = "alias record -> CloudFront", permissionNote = "public", routeNote = "global edge network" } });
            t.connections.Add(new ConnectionSpec { id = "c_cf_alb", fromBlockId = "cloudfront", toBlockId = "alb", flow = ConnectionFlowKind.Request, plainSummary = "No local copy? The pickup point asks the front desk.", requirement = new ConnectionRequirement { addressNote = "ALB DNS app-alb-123.eu-west-1.elb.amazonaws.com", permissionNote = "front desk lets the public in on 443", securityGroup = new SecurityGroupRule("inbound", "TCP", "443", "0.0.0.0/0"), routeNote = "front desk sits in the public area with a road to the outside" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A", fromBlockId = "alb", toBlockId = "ec2A", flow = ConnectionFlowKind.Request, plainSummary = "The front desk sends the visitor to a free, healthy worker.", requirement = new ConnectionRequirement { addressNote = "worker registered at the desk (target group)", permissionNote = "worker only lets in the front desk (its SG)", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "front-desk SG"), routeNote = "same plot; back area reachable from the front area" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A2", fromBlockId = "alb", toBlockId = "ec2A2", flow = ConnectionFlowKind.Request, plainSummary = "The newly hired worker is signed in and starts taking visitors.", requirement = new ConnectionRequirement { addressNote = "auto-registered at the desk", permissionNote = "inherits the worker guest list", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "front-desk SG"), routeNote = "same plot, back area" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2B", fromBlockId = "alb", toBlockId = "ec2B", flow = ConnectionFlowKind.Request, plainSummary = "Visitors also go to the worker in the other neighbourhood.", requirement = new ConnectionRequirement { addressNote = "worker registered at the desk", permissionNote = "worker only lets in the front desk", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "front-desk SG"), routeNote = "same plot; back area in neighbourhood B" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2A_rds", fromBlockId = "ec2A", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The worker looks something up in the records office.", requirement = new ConnectionRequirement { addressNote = "records endpoint app-db.abc.eu-west-1.rds.amazonaws.com:5432", permissionNote = "records office only lets in workers; the worker wears a key to read the credentials", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "worker SG"), iam = new IamGrant("worker-reads-db-secret", "secretsmanager:GetSecretValue"), routeNote = "same plot, back areas" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2B_rds", fromBlockId = "ec2B", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The worker in the other neighbourhood uses the same records office.", requirement = new ConnectionRequirement { addressNote = "same records endpoint", permissionNote = "records office lets in workers", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "worker SG"), routeNote = "across neighbourhoods, within the plot" } });
            t.connections.Add(new ConnectionSpec { id = "c_rds_sync", fromBlockId = "rdsPrimary", toBlockId = "rdsStandby", flow = ConnectionFlowKind.Replication, plainSummary = "The records office keeps the backup in constant sync.", requirement = new ConnectionRequirement { addressNote = "internal Multi-AZ replication", permissionNote = "managed by RDS", routeNote = "across neighbourhoods, within the plot" } });

            // ---------- The 9-stage journey (problem-first, town language) ----------
            t.stages.Add(new StageSpec { index = 0, title = "One shop, one clerk", focusBlockId = "singleServer", animation = StageAnimation.Overload, narration = "Picture your app as a single shop with one clerk. A few visitors? Fine. But word spreads, a crowd piles in, and the clerk is swamped — the queue jams and the shop seizes up. One clerk, one point of failure.", concept = "One of anything is a single point of failure.", visibleBlockIds = Ids("user", "singleServer"), visibleConnectionIds = Ids("c_user_server") });
            t.stages.Add(new StageSpec { index = 1, title = "Two neighbourhoods", focusBlockId = "region", narration = "First, somewhere safe to build. AWS gives you a Region (a city) split into Availability Zones — separate neighbourhoods with their own power and water. Build across two, and if one loses power, the other keeps serving.", concept = "Spread across AZs so losing one doesn't take you down.", visibleBlockIds = Ids("region", "azA", "azB") });
            t.stages.Add(new StageSpec { index = 2, title = "Your gated plot", focusBlockId = "vpc", narration = "Rent a gated plot of land — your VPC. Its address range, 10.0.0.0/16, is just how many street numbers the plot gets. Fence it into areas: front areas with a gate to the public road, back areas with no public gate.", concept = "Public vs private = whether there's a road in from outside.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw") });
            t.stages.Add(new StageSpec { index = 3, title = "Workers out back", focusBlockId = "ec2A", narration = "Move the people doing the real work — your servers — into the private back areas. Nobody can walk in off the street to reach them; everything must come through the front. Safer, and you decide exactly who gets in.", concept = "Keep the workers private; expose only the front.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B") });
            t.stages.Add(new StageSpec { index = 4, title = "A front desk", focusBlockId = "alb", animation = StageAnimation.Pulse, animationConnectionId = "c_alb_ec2A", narration = "With more than one worker, who does a visitor talk to? Add a front desk at the public entrance — the load balancer. Every visitor checks in there and is sent to a free, healthy worker. If a worker stops answering, the desk quietly stops sending people their way.", concept = "The front desk spreads visitors and hides any one worker failing.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B") });
            t.stages.Add(new StageSpec { index = 5, title = "Hire on demand", focusBlockId = "asg", animation = StageAnimation.Spike, narration = "A rush hits. Instead of a fixed crew, the Auto Scaling group hires extra workers when the queue grows and lets them go when it's quiet — watch a new worker appear to take the load. You never run out of hands, and you don't pay for idle ones.", concept = "Capacity follows demand, automatically.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2") });
            t.stages.Add(new StageSpec { index = 6, title = "The records office", focusBlockId = "rdsPrimary", animation = StageAnimation.Pulse, animationConnectionId = "c_ec2A_rds", narration = "Workers need one shared source of truth — the records office (the database). Put the main office in one neighbourhood and a live backup in the other, kept in constant sync. If the main office's neighbourhood goes dark, the backup takes over on its own.", concept = "Multi-AZ database = a hot backup that fails over automatically.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 7, title = "Signpost & pickup point", focusBlockId = "route53", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_ec2A_rds"), narration = "Finally, help far-away visitors. Route 53 is the signpost that turns your name into directions; CloudFront is a local pickup point that keeps copies nearby. Follow one request the whole way: visitor -> signpost -> pickup point -> front desk -> worker -> records office.", concept = "Point people with DNS; serve them locally with a CDN.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 8, title = "Lose a neighbourhood, stay open", focusBlockId = "azA", animation = StageAnimation.Failover, narration = "Now the disaster from the start. A whole neighbourhood (A) goes dark — its worker and the main records office vanish. But the front desk just routes everyone to the other neighbourhood, and the backup office takes over. The shop stays open. That's high availability.", concept = "High availability = survive losing a whole AZ, with nobody left waiting.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });

            // ---------- Assessment ----------
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Your VPC (the plot) is 10.0.0.0/16. Which is a valid, correctly-sized area (subnet) inside it?", options = new[] { "10.0.1.0/24", "192.168.1.0/24", "10.0.0.0/8", "11.0.0.0/24" }, correctIndices = new[] { 0 }, explanation = "A subnet must sit inside the plot's range and be smaller. 10.0.1.0/24 is inside 10.0.0.0/16. A /8 is bigger than a /16, and the other ranges are outside the plot." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why are the workers (EC2) kept in the private back areas?", options = new[] { "So nobody on the street can reach them directly", "Because back areas are faster", "Because back areas are cheaper", "So they don't need a front desk" }, correctIndices = new[] { 0 }, explanation = "Private areas have no road in from the public street; visitors must come through the public-facing front desk." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.MultiChoice, prompt = "The shop must stay open if a whole neighbourhood loses power. Which TWO are required? (pick two)", options = new[] { "Workers in at least two neighbourhoods behind the front desk", "A records office with a live backup in the other neighbourhood", "One bigger, stronger worker", "Keep all records on one worker's own desk" }, correctIndices = new[] { 0, 1 }, explanation = "Surviving a neighbourhood (AZ) outage needs redundancy across neighbourhoods for both the work (multiple AZs behind the desk) and the data (Multi-AZ records office)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "What does the records office's live backup (RDS Multi-AZ) mainly give you?", options = new[] { "Automatic takeover if the main office fails", "Faster reads", "Cheaper storage", "A global pickup network" }, correctIndices = new[] { 0 }, explanation = "Multi-AZ is about staying available: a synchronous standby and automatic failover — not extra read speed (that's read replicas)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "How does the front desk avoid sending visitors to a broken worker?", options = new[] { "Health checks — it stops sending people to workers that fail them", "It restarts the worker", "It serves a cached answer instead", "It hires a bigger worker" }, correctIndices = new[] { 0 }, explanation = "The load balancer continuously health-checks its workers and only routes to healthy ones." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "Visitors get no answer, yet every worker is fine. The front desk was put in a private back area. Tap the thing in the scene that must move to the public front area to fix this.", tapTargetBlockId = "alb", explanation = "The front desk (load balancer) must sit in the public area, with a road to the outside, so street visitors can reach it. The workers stay private behind it." });

            return t;
        }
    }
}
