using System.Collections.Generic;
using UnityEngine;

namespace LearnAWS.Content
{
    /// <summary>
    /// Authors the Solutions Architect course in code. This is the single seam where, later, content can be
    /// loaded from ScriptableObjects/JSON instead — callers only ever see <see cref="CourseSpec"/>.
    /// v1 ships one fully-built topic: "Build a Highly Available Web App".
    /// </summary>
    public static class SolutionsArchitectContent
    {
        public static CourseSpec BuildCourse()
        {
            return new CourseSpec
            {
                id = "saa-c03",
                title = "AWS Solutions Architect",
                topics = new List<TopicSpec> { BuildHighlyAvailableWebApp() }
            };
        }

        private static List<string> Ids(params string[] s) => new List<string>(s);

        private static TopicSpec BuildHighlyAvailableWebApp()
        {
            var t = new TopicSpec
            {
                id = "ha-web-app",
                title = "Build a Highly Available Web App",
                examDomain = "Design Resilient Architectures",
                summary = "Assemble the classic resilient web architecture piece by piece, then watch it survive an Availability Zone failure."
            };

            // ---------- Containers (drawn as wireframe "plots / fences") ----------
            t.blocks.Add(new BlockSpec { id = "region", kind = AwsBlockKind.Region, displayName = "Region (eu-west-1)", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.4f, 0), size = new Vector3(14f, 3.2f, 10f), plainSummary = "The ground you build on — a geographic area such as eu-west-1.", realSummary = "Region eu-west-1 (Ireland). Contains multiple isolated Availability Zones." });
            t.blocks.Add(new BlockSpec { id = "azA", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), plainSummary = "An isolated tile of the region with its own power and network.", realSummary = "Availability Zone eu-west-1a." });
            t.blocks.Add(new BlockSpec { id = "azB", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), plainSummary = "A second isolated tile, so one can fail and you stay up.", realSummary = "Availability Zone eu-west-1b." });
            t.blocks.Add(new BlockSpec { id = "vpc", kind = AwsBlockKind.Vpc, displayName = "VPC", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.1f, 0.3f), size = new Vector3(12.6f, 2.4f, 8.2f), cidr = new CidrInfo("10.0.0.0", 16), arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "vpc/vpc-0a1b2c3d"), plainSummary = "Your walled private plot inside the region.", realSummary = "VPC 10.0.0.0/16 — 65,536 private addresses to carve into subnets." });
            t.blocks.Add(new BlockSpec { id = "pubA", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), cidr = new CidrInfo("10.0.0.0", 24), plainSummary = "A fenced area with a road to the internet gateway.", realSummary = "Public subnet 10.0.0.0/24 (eu-west-1a). Route table sends 0.0.0.0/0 to the internet gateway." });
            t.blocks.Add(new BlockSpec { id = "pubB", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), cidr = new CidrInfo("10.0.1.0", 24), plainSummary = "The matching public area in the second AZ.", realSummary = "Public subnet 10.0.1.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "privA", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), cidr = new CidrInfo("10.0.2.0", 24), plainSummary = "A fenced area with no direct road from the internet.", realSummary = "Private subnet 10.0.2.0/24 (eu-west-1a)." });
            t.blocks.Add(new BlockSpec { id = "privB", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), cidr = new CidrInfo("10.0.3.0", 24), plainSummary = "The matching private area in the second AZ.", realSummary = "Private subnet 10.0.3.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "asg", kind = AwsBlockKind.AutoScalingGroup, displayName = "Auto Scaling group", category = ServiceCategory.Compute, isContainer = true, position = new Vector3(0, 0.7f, 2.0f), size = new Vector3(12.6f, 1.5f, 3.8f), plainSummary = "A flexible boundary that adds or removes servers to match demand.", realSummary = "Auto Scaling group spanning both private subnets; min/desired/max instances scale on a metric." });

            // ---------- Service blocks (cubes with nameplates) ----------
            t.blocks.Add(new BlockSpec { id = "user", kind = AwsBlockKind.User, displayName = "Global user", category = ServiceCategory.Generic, position = new Vector3(0, 3.3f, -8.6f), plainSummary = "A person opening your app from somewhere in the world.", realSummary = "Client HTTPS request to your domain." });
            t.blocks.Add(new BlockSpec { id = "singleServer", kind = AwsBlockKind.GenericServer, displayName = "The one server", category = ServiceCategory.Compute, position = new Vector3(0, 0.7f, -1.2f), plainSummary = "One server doing everything. Fine — until traffic spikes or it dies.", realSummary = "A single public EC2 instance. No redundancy: a single point of failure." });
            t.blocks.Add(new BlockSpec { id = "igw", kind = AwsBlockKind.InternetGateway, displayName = "Internet gateway", category = ServiceCategory.Networking, position = new Vector3(0, 1.9f, -4.6f), plainSummary = "The one road between your plot and the public internet.", realSummary = "Internet gateway attached to the VPC; only public subnets route to it." });
            t.blocks.Add(new BlockSpec { id = "alb", kind = AwsBlockKind.ApplicationLoadBalancer, displayName = "Application Load Balancer", category = ServiceCategory.Networking, position = new Vector3(0, 1.2f, -1.6f), endpoint = "app-alb-123.eu-west-1.elb.amazonaws.com", ports = new[] { "80", "443" }, arn = new ArnInfo("elasticloadbalancing", "eu-west-1", "123456789012", "loadbalancer/app/app-alb/50dc"), plainSummary = "The receptionist: sends each visitor to a free, healthy desk.", realSummary = "Internet-facing ALB across both public subnets; health-checks targets and drops unhealthy ones." });
            t.blocks.Add(new BlockSpec { id = "ec2A", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A", category = ServiceCategory.Compute, position = new Vector3(-3.8f, 0.7f, 1.7f), ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa1"), plainSummary = "A web server doing the real work — kept off the public internet.", realSummary = "EC2 in private subnet A; only the ALB's security group may reach port 80." });
            t.blocks.Add(new BlockSpec { id = "ec2A2", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A2 (scaled out)", category = ServiceCategory.Compute, position = new Vector3(-2.4f, 0.7f, 2.7f), ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa2"), plainSummary = "An extra server the Auto Scaling group launched when traffic rose.", realSummary = "EC2 added by the Auto Scaling group during a scale-out event." });
            t.blocks.Add(new BlockSpec { id = "ec2B", kind = AwsBlockKind.Ec2Instance, displayName = "Web server B", category = ServiceCategory.Compute, position = new Vector3(3.8f, 0.7f, 1.7f), ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0bb1"), plainSummary = "A web server in the second AZ, so losing one AZ doesn't take you down.", realSummary = "EC2 in private subnet B." });
            t.blocks.Add(new BlockSpec { id = "rdsPrimary", kind = AwsBlockKind.RdsPrimary, displayName = "RDS primary", category = ServiceCategory.Database, position = new Vector3(-3.5f, 0.7f, 3.5f), endpoint = "app-db.abc.eu-west-1.rds.amazonaws.com:5432", arn = new ArnInfo("rds", "eu-west-1", "123456789012", "db:app-db"), plainSummary = "Where the app's data lives — the source of truth.", realSummary = "RDS primary (Multi-AZ) in eu-west-1a with a synchronous standby in 1b." });
            t.blocks.Add(new BlockSpec { id = "rdsStandby", kind = AwsBlockKind.RdsStandby, displayName = "RDS standby", category = ServiceCategory.Database, position = new Vector3(3.5f, 0.7f, 3.5f), plainSummary = "A hot copy ready to take over instantly if the primary's AZ fails.", realSummary = "RDS standby in eu-west-1b; promoted automatically on failover." });
            t.blocks.Add(new BlockSpec { id = "cloudfront", kind = AwsBlockKind.CloudFront, displayName = "CloudFront", category = ServiceCategory.Edge, position = new Vector3(2.4f, 3.0f, -6.9f), endpoint = "d111abcdef.cloudfront.net", plainSummary = "Caches content close to users worldwide for speed.", realSummary = "CloudFront distribution; origin = the ALB." });
            t.blocks.Add(new BlockSpec { id = "route53", kind = AwsBlockKind.Route53, displayName = "Route 53", category = ServiceCategory.Edge, position = new Vector3(-2.4f, 3.0f, -6.9f), plainSummary = "The switchboard that turns your domain name into the right address.", realSummary = "Route 53 hosted zone; alias record app.example.com -> CloudFront." });

            // ---------- Connections (with the three-gates requirement detail) ----------
            t.connections.Add(new ConnectionSpec { id = "c_user_server", fromBlockId = "user", toBlockId = "singleServer", flow = ConnectionFlowKind.Request, plainSummary = "The visitor hits the one server directly.", requirement = new ConnectionRequirement { addressNote = "the server's public IP", permissionNote = "security group allows 80 from anywhere", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "0.0.0.0/0"), routeNote = "public subnet with a route to the internet" } });
            t.connections.Add(new ConnectionSpec { id = "c_user_r53", fromBlockId = "user", toBlockId = "route53", flow = ConnectionFlowKind.Request, plainSummary = "The browser asks DNS where app.example.com lives.", requirement = new ConnectionRequirement { addressNote = "your domain name app.example.com", permissionNote = "public DNS, no permission needed", routeNote = "public internet" } });
            t.connections.Add(new ConnectionSpec { id = "c_r53_cf", fromBlockId = "route53", toBlockId = "cloudfront", flow = ConnectionFlowKind.Request, plainSummary = "DNS points the name at the CDN.", requirement = new ConnectionRequirement { addressNote = "alias record -> CloudFront distribution", permissionNote = "public", routeNote = "global edge network" } });
            t.connections.Add(new ConnectionSpec { id = "c_cf_alb", fromBlockId = "cloudfront", toBlockId = "alb", flow = ConnectionFlowKind.Request, plainSummary = "CloudFront forwards uncached requests to the load balancer.", requirement = new ConnectionRequirement { addressNote = "ALB DNS app-alb-123.eu-west-1.elb.amazonaws.com", permissionNote = "ALB security group allows 443 from the internet", securityGroup = new SecurityGroupRule("inbound", "TCP", "443", "0.0.0.0/0"), routeNote = "ALB sits in public subnets with a route to the internet gateway" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A", fromBlockId = "alb", toBlockId = "ec2A", flow = ConnectionFlowKind.Request, plainSummary = "The load balancer forwards the visitor to a healthy web server.", requirement = new ConnectionRequirement { addressNote = "instance registered as a target in the target group", permissionNote = "instance SG allows 80 from the ALB's SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "web-alb SG"), routeNote = "same VPC; private subnet reachable from the ALB's subnets" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A2", fromBlockId = "alb", toBlockId = "ec2A2", flow = ConnectionFlowKind.Request, plainSummary = "The new scaled-out server is registered and starts taking traffic.", requirement = new ConnectionRequirement { addressNote = "auto-registered target", permissionNote = "inherits the web-tier SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "web-alb SG"), routeNote = "same VPC private subnet" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2B", fromBlockId = "alb", toBlockId = "ec2B", flow = ConnectionFlowKind.Request, plainSummary = "Traffic also goes to the server in the other AZ.", requirement = new ConnectionRequirement { addressNote = "instance registered as a target", permissionNote = "instance SG allows 80 from the ALB's SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "web-alb SG"), routeNote = "same VPC; private subnet in AZ B" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2A_rds", fromBlockId = "ec2A", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The web server queries the database for data.", requirement = new ConnectionRequirement { addressNote = "DB endpoint app-db.abc.eu-west-1.rds.amazonaws.com:5432", permissionNote = "DB SG allows 5432 from the web SG; the server wears a role to read DB credentials", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "web-tier SG"), iam = new IamGrant("web-reads-db-secret", "secretsmanager:GetSecretValue"), routeNote = "same VPC, private subnets" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2B_rds", fromBlockId = "ec2B", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The server in AZ B talks to the same primary database.", requirement = new ConnectionRequirement { addressNote = "same DB endpoint", permissionNote = "DB SG allows 5432 from the web SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "web-tier SG"), routeNote = "cross-AZ within the VPC" } });
            t.connections.Add(new ConnectionSpec { id = "c_rds_sync", fromBlockId = "rdsPrimary", toBlockId = "rdsStandby", flow = ConnectionFlowKind.Replication, plainSummary = "The primary keeps the standby in sync, synchronously.", requirement = new ConnectionRequirement { addressNote = "internal Multi-AZ replication", permissionNote = "managed by RDS", routeNote = "cross-AZ within the VPC" } });

            // ---------- The 9-stage journey ----------
            t.stages.Add(new StageSpec { index = 0, title = "One server, one user", focusBlockId = "singleServer", animation = StageAnimation.Spike, narration = "Meet the simplest setup: one user, one server. It works fine — until traffic spikes or the server's hardware fails. Watch it buckle under a surge.", concept = "A single server is a single point of failure.", visibleBlockIds = Ids("user", "singleServer"), visibleConnectionIds = Ids("c_user_server") });
            t.stages.Add(new StageSpec { index = 1, title = "Region & Availability Zones", focusBlockId = "region", narration = "AWS gives you Regions (geographic areas) split into Availability Zones — isolated tiles with their own power and networking. Building across two AZs means one can fail and you stay up.", concept = "Multi-AZ shrinks your blast radius.", visibleBlockIds = Ids("region", "azA", "azB") });
            t.stages.Add(new StageSpec { index = 2, title = "VPC & subnets", focusBlockId = "vpc", narration = "Inside the region you fence off a private plot — a VPC, 10.0.0.0/16. You carve it into subnets: public ones with a road to the internet gateway, private ones without. Notice each subnet (10.0.0.0/24) is a small slice of the VPC's /16.", concept = "Public vs private = whether there is a route to the internet.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw") });
            t.stages.Add(new StageSpec { index = 3, title = "Compute in private subnets", focusBlockId = "ec2A", narration = "Place your web servers (EC2) in the private subnets. They do the real work but stay off the public internet — nothing out there can reach them directly.", concept = "Keep app servers private; expose only what must be public.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B") });
            t.stages.Add(new StageSpec { index = 4, title = "Load balancing", focusBlockId = "alb", animation = StageAnimation.Pulse, animationConnectionId = "c_alb_ec2A", narration = "Put an Application Load Balancer in the public subnets. It's the receptionist: every visitor hits the ALB, which forwards them to a healthy server and quietly stops routing to any that fail its health checks.", concept = "A load balancer spreads traffic and hides individual failures.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B") });
            t.stages.Add(new StageSpec { index = 5, title = "Auto Scaling", focusBlockId = "asg", animation = StageAnimation.Spike, narration = "Wrap the servers in an Auto Scaling group. When traffic spikes it launches more instances; when it's quiet it removes them — you only pay for what you need and never run out of desks.", concept = "Elasticity: capacity follows demand automatically.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2") });
            t.stages.Add(new StageSpec { index = 6, title = "Database (Multi-AZ)", focusBlockId = "rdsPrimary", animation = StageAnimation.Pulse, animationConnectionId = "c_ec2A_rds", narration = "Add a managed database. With Multi-AZ, RDS keeps a synchronous standby in the other AZ. If the primary's AZ fails, RDS promotes the standby automatically — your data survives.", concept = "Multi-AZ RDS = durability + automatic failover (not read scaling).", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 7, title = "Edge & DNS", focusBlockId = "route53", animation = StageAnimation.Pulse, animationConnectionId = "c_user_r53", narration = "Finally, front it globally. Route 53 turns your domain into an address and CloudFront caches content at edge locations near each user. A request now flows user -> Route 53 -> CloudFront -> ALB -> server -> database.", concept = "Edge + DNS cut latency and absorb load near the user.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 8, title = "Survive the failure", focusBlockId = "azA", animation = StageAnimation.Failover, narration = "Now re-run the disaster. Availability Zone A goes dark — its server and the database primary vanish. But the load balancer simply routes everyone to AZ B and RDS promotes the standby. The app stays up. That is a highly available architecture.", concept = "HA = no single point of failure; the system survives losing a whole AZ.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });

            // ---------- Assessment ----------
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Your VPC is 10.0.0.0/16. Which is a valid, correctly-sized subnet inside it?", options = new[] { "10.0.1.0/24", "192.168.1.0/24", "10.0.0.0/8", "11.0.0.0/24" }, correctIndices = new[] { 0 }, explanation = "A subnet must fall inside the VPC's range and be smaller. 10.0.1.0/24 sits inside 10.0.0.0/16. A /8 is bigger than a /16, and the other ranges are outside the VPC." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why are the EC2 web servers placed in private subnets?", options = new[] { "So nothing on the internet can reach them directly", "Because private subnets are faster", "Because private subnets are cheaper", "So they don't need a load balancer" }, correctIndices = new[] { 0 }, explanation = "Private subnets have no route from the internet; traffic must arrive via the public-facing load balancer." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.MultiChoice, prompt = "The app must survive one Availability Zone failing. Which TWO are required? (pick two)", options = new[] { "Run servers in at least two AZs behind the load balancer", "Use a Multi-AZ RDS database", "Use one larger EC2 instance", "Store everything on one server's local disk" }, correctIndices = new[] { 0, 1 }, explanation = "Surviving an AZ outage needs redundancy across AZs for both compute (multiple AZs behind the ALB) and data (Multi-AZ RDS)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "What does RDS Multi-AZ primarily give you?", options = new[] { "Automatic failover to a standby for high availability", "More read throughput", "Lower storage cost", "A global content cache" }, correctIndices = new[] { 0 }, explanation = "Multi-AZ provides availability via a synchronous standby and automatic failover — not extra read capacity (that's read replicas)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "How does the load balancer avoid sending visitors to a broken server?", options = new[] { "Health checks — it stops routing to targets that fail them", "It restarts the broken server", "It caches the response instead", "It switches to a bigger instance" }, correctIndices = new[] { 0 }, explanation = "The ALB continuously health-checks its targets and only routes to healthy ones." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "Users get no response, yet every server is healthy. The load balancer was placed in the PRIVATE subnets. Tap the component in the scene that must move to the public subnets to fix this.", tapTargetBlockId = "alb", explanation = "The ALB must sit in public subnets (with a route to the internet gateway) so internet users can reach it. The servers stay private behind it." });

            return t;
        }
    }
}
