using System.Collections.Generic;
using UnityEngine;

namespace LearnAWS.Content
{
    /// <summary>
    /// Authors the Solutions Architect course in code. The single seam where, later, content can be loaded
    /// from ScriptableObjects/JSON instead — callers only ever see <see cref="CourseSpec"/>.
    ///
    /// Two lenses on the same topic:
    ///  - Architecture view: real AWS topology + icons, plain-AWS narration.
    ///  - Story view: a restaurant kitchen *service line* (a left-to-right flow, two parallel kitchen lines for
    ///    redundancy), with its own kitchen narration. storyPosition/storyName drive that layout.
    /// </summary>
    public static class SolutionsArchitectContent
    {
        public static CourseSpec BuildCourse()
        {
            return new CourseSpec
            {
                id = "saa-c03",
                title = "AWS Solutions Architect",
                topics = new List<TopicSpec> { BuildHighlyAvailableWebApp(), BuildStorage(), BuildIam(), BuildNetworking(), BuildMessaging() }
            };
        }

        private static List<string> Ids(params string[] s) => new List<string>(s);

        private static TopicSpec BuildHighlyAvailableWebApp()
        {
            var t = new TopicSpec
            {
                id = "ha-web-app",
                title = "Build a Highly Available Web App",
                examDomain = "Design Resilient Architectures",
                summary = "Run a kitchen that survives the dinner rush, a cook walking off, and a whole kitchen flooding.",
                sceneryStyle = StorySceneryStyle.KitchenLines
            };

            // ---------- Containers. Architecture: wireframe plots. Story: the restaurant / its two kitchen lines. ----------
            t.blocks.Add(new BlockSpec { id = "region", kind = AwsBlockKind.Region, displayName = "Region (eu-west-1)", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.4f, 0), size = new Vector3(14f, 3.2f, 10f), storyPosition = new Vector3(-1f, 0.7f, 0f), storyName = "The restaurant", plainSummary = "A geographic area such as eu-west-1.", realSummary = "Region eu-west-1 (Ireland). Contains multiple isolated Availability Zones." });
            t.blocks.Add(new BlockSpec { id = "azA", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), storyPosition = new Vector3(2.5f, 0.7f, -2.2f), storyName = "Kitchen line A", plainSummary = "An isolated zone with its own power and network.", realSummary = "Availability Zone eu-west-1a." });
            t.blocks.Add(new BlockSpec { id = "azB", kind = AwsBlockKind.AvailabilityZone, displayName = "Availability Zone B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 1.2f, 0), size = new Vector3(6.4f, 2.6f, 9f), storyPosition = new Vector3(2.5f, 0.7f, 2.2f), storyName = "Kitchen line B", plainSummary = "A second isolated zone, so one can fail and you stay up.", realSummary = "Availability Zone eu-west-1b." });
            t.blocks.Add(new BlockSpec { id = "vpc", kind = AwsBlockKind.Vpc, displayName = "VPC", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(0, 1.1f, 0.3f), size = new Vector3(12.6f, 2.4f, 8.2f), storyPosition = new Vector3(1.5f, 0.7f, 0f), storyName = "The kitchen", cidr = new CidrInfo("10.0.0.0", 16), arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "vpc/vpc-0a1b2c3d"), plainSummary = "Your private network inside the region.", realSummary = "VPC 10.0.0.0/16 — 65,536 private addresses to carve into subnets." });
            t.blocks.Add(new BlockSpec { id = "pubA", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), storyPosition = new Vector3(-3.5f, 0.7f, -1.5f), storyName = "Front of house A", cidr = new CidrInfo("10.0.0.0", 24), plainSummary = "A subnet with a route to the internet gateway.", realSummary = "Public subnet 10.0.0.0/24 (eu-west-1a); routes 0.0.0.0/0 to the internet gateway." });
            t.blocks.Add(new BlockSpec { id = "pubB", kind = AwsBlockKind.PublicSubnet, displayName = "Public subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, -2.4f), size = new Vector3(5.6f, 1.6f, 3.2f), storyPosition = new Vector3(-3.5f, 0.7f, 1.5f), storyName = "Front of house B", cidr = new CidrInfo("10.0.1.0", 24), plainSummary = "The public subnet in the second AZ.", realSummary = "Public subnet 10.0.1.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "privA", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet A", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(-3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), storyPosition = new Vector3(2.5f, 0.7f, -2.2f), storyName = "The line A", cidr = new CidrInfo("10.0.2.0", 24), plainSummary = "A subnet with no inbound route from the internet.", realSummary = "Private subnet 10.0.2.0/24 (eu-west-1a)." });
            t.blocks.Add(new BlockSpec { id = "privB", kind = AwsBlockKind.PrivateSubnet, displayName = "Private subnet B", category = ServiceCategory.Networking, isContainer = true, position = new Vector3(3.5f, 0.8f, 2.0f), size = new Vector3(5.6f, 1.6f, 3.6f), storyPosition = new Vector3(2.5f, 0.7f, 2.2f), storyName = "The line B", cidr = new CidrInfo("10.0.3.0", 24), plainSummary = "The private subnet in the second AZ.", realSummary = "Private subnet 10.0.3.0/24 (eu-west-1b)." });
            t.blocks.Add(new BlockSpec { id = "asg", kind = AwsBlockKind.AutoScalingGroup, displayName = "Auto Scaling group", category = ServiceCategory.Compute, isContainer = true, position = new Vector3(0, 0.7f, 2.0f), size = new Vector3(12.6f, 1.5f, 3.8f), storyPosition = new Vector3(1.8f, 0.7f, 0f), storyName = "The brigade", plainSummary = "Scales the number of instances to match demand.", realSummary = "Auto Scaling group spanning both private subnets; min/desired/max scale on a metric." });

            // ---------- Service blocks ----------
            t.blocks.Add(new BlockSpec { id = "user", kind = AwsBlockKind.User, displayName = "Global user", category = ServiceCategory.Generic, position = new Vector3(0, 3.3f, -8.6f), storyPosition = new Vector3(-9f, 0.7f, 0f), storyName = "Customer", plainSummary = "A person opening your app from somewhere in the world.", realSummary = "Client HTTPS request to your domain." });
            t.blocks.Add(new BlockSpec { id = "singleServer", kind = AwsBlockKind.GenericServer, displayName = "The one server", category = ServiceCategory.Compute, position = new Vector3(0, 0.7f, -1.2f), storyPosition = new Vector3(-2f, 0.7f, 0f), storyName = "The one cook", plainSummary = "One instance doing everything. Fine — until traffic spikes or it fails.", realSummary = "A single public EC2 instance. No redundancy: a single point of failure." });
            t.blocks.Add(new BlockSpec { id = "igw", kind = AwsBlockKind.InternetGateway, displayName = "Internet gateway", category = ServiceCategory.Networking, position = new Vector3(0, 1.9f, -4.6f), storyPosition = new Vector3(-4.6f, 0.7f, 0f), storyName = "Service door", plainSummary = "The single route between your network and the internet.", realSummary = "Internet gateway attached to the VPC; only public subnets route to it." });
            t.blocks.Add(new BlockSpec { id = "alb", kind = AwsBlockKind.ApplicationLoadBalancer, displayName = "Application Load Balancer", category = ServiceCategory.Networking, position = new Vector3(0, 1.2f, -1.6f), storyPosition = new Vector3(-2f, 0.7f, 0f), storyName = "The pass", endpoint = "app-alb-123.eu-west-1.elb.amazonaws.com", ports = new[] { "80", "443" }, arn = new ArnInfo("elasticloadbalancing", "eu-west-1", "123456789012", "loadbalancer/app/app-alb/50dc"), plainSummary = "Routes each request to a healthy target and drops unhealthy ones.", realSummary = "Internet-facing ALB across both public subnets; health-checks targets." });
            t.blocks.Add(new BlockSpec { id = "ec2A", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A", category = ServiceCategory.Compute, position = new Vector3(-3.8f, 0.7f, 1.7f), storyPosition = new Vector3(1f, 0.7f, -2.2f), storyName = "Cook A", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa1"), plainSummary = "A web server doing the work, in a private subnet.", realSummary = "EC2 in private subnet A; only the ALB's security group may reach port 80." });
            t.blocks.Add(new BlockSpec { id = "ec2A2", kind = AwsBlockKind.Ec2Instance, displayName = "Web server A2 (scaled out)", category = ServiceCategory.Compute, position = new Vector3(-2.4f, 0.7f, 2.7f), storyPosition = new Vector3(2.6f, 0.7f, -2.2f), storyName = "Extra cook", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0aa2"), plainSummary = "An instance launched by Auto Scaling during a spike.", realSummary = "EC2 added by the Auto Scaling group during a scale-out event." });
            t.blocks.Add(new BlockSpec { id = "ec2B", kind = AwsBlockKind.Ec2Instance, displayName = "Web server B", category = ServiceCategory.Compute, position = new Vector3(3.8f, 0.7f, 1.7f), storyPosition = new Vector3(1f, 0.7f, 2.2f), storyName = "Cook B", ports = new[] { "80" }, arn = new ArnInfo("ec2", "eu-west-1", "123456789012", "instance/i-0bb1"), plainSummary = "A web server in the second AZ.", realSummary = "EC2 in private subnet B." });
            t.blocks.Add(new BlockSpec { id = "rdsPrimary", kind = AwsBlockKind.RdsPrimary, displayName = "RDS primary", category = ServiceCategory.Database, position = new Vector3(-3.5f, 0.7f, 3.5f), storyPosition = new Vector3(4.6f, 0.7f, -2.2f), storyName = "Pantry", endpoint = "app-db.abc.eu-west-1.rds.amazonaws.com:5432", arn = new ArnInfo("rds", "eu-west-1", "123456789012", "db:app-db"), plainSummary = "The database — the single source of truth.", realSummary = "RDS primary (Multi-AZ) in eu-west-1a with a synchronous standby in 1b." });
            t.blocks.Add(new BlockSpec { id = "rdsStandby", kind = AwsBlockKind.RdsStandby, displayName = "RDS standby", category = ServiceCategory.Database, position = new Vector3(3.5f, 0.7f, 3.5f), storyPosition = new Vector3(4.6f, 0.7f, 2.2f), storyName = "Backup pantry", plainSummary = "A synchronous copy ready to take over on failover.", realSummary = "RDS standby in eu-west-1b; promoted automatically on failover." });
            t.blocks.Add(new BlockSpec { id = "cloudfront", kind = AwsBlockKind.CloudFront, displayName = "CloudFront", category = ServiceCategory.Edge, position = new Vector3(2.4f, 3.0f, -6.9f), storyPosition = new Vector3(-6.6f, 0.7f, 1.1f), storyName = "Grab-and-go", endpoint = "d111abcdef.cloudfront.net", plainSummary = "Caches content at edge locations near each user.", realSummary = "CloudFront distribution; origin = the ALB." });
            t.blocks.Add(new BlockSpec { id = "route53", kind = AwsBlockKind.Route53, displayName = "Route 53", category = ServiceCategory.Edge, position = new Vector3(-2.4f, 3.0f, -6.9f), storyPosition = new Vector3(-6.6f, 0.7f, -1.1f), storyName = "Host stand", plainSummary = "Turns your domain name into the right address.", realSummary = "Route 53 hosted zone; alias record app.example.com -> CloudFront." });

            // ---------- Connections (with the three-questions requirement detail) ----------
            t.connections.Add(new ConnectionSpec { id = "c_user_server", fromBlockId = "user", toBlockId = "singleServer", flow = ConnectionFlowKind.Request, plainSummary = "The customer orders straight from the one cook.", requirement = new ConnectionRequirement { addressNote = "the instance's public IP", permissionNote = "security group allows 80 from anywhere", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "0.0.0.0/0"), routeNote = "public subnet with a route to the internet" } });
            t.connections.Add(new ConnectionSpec { id = "c_user_r53", fromBlockId = "user", toBlockId = "route53", flow = ConnectionFlowKind.Request, plainSummary = "Where is it? The customer asks the host stand.", requirement = new ConnectionRequirement { addressNote = "your domain name app.example.com", permissionNote = "public DNS, no permission needed", routeNote = "public internet" } });
            t.connections.Add(new ConnectionSpec { id = "c_r53_cf", fromBlockId = "route53", toBlockId = "cloudfront", flow = ConnectionFlowKind.Request, plainSummary = "The host points to the nearest grab-and-go counter.", requirement = new ConnectionRequirement { addressNote = "alias record -> CloudFront", permissionNote = "public", routeNote = "global edge network" } });
            t.connections.Add(new ConnectionSpec { id = "c_cf_alb", fromBlockId = "cloudfront", toBlockId = "alb", flow = ConnectionFlowKind.Request, plainSummary = "Not ready-made? The counter sends the order to the pass.", requirement = new ConnectionRequirement { addressNote = "ALB DNS app-alb-123.eu-west-1.elb.amazonaws.com", permissionNote = "ALB SG allows 443 from the internet", securityGroup = new SecurityGroupRule("inbound", "TCP", "443", "0.0.0.0/0"), routeNote = "ALB sits in public subnets with a route to the internet gateway" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A", fromBlockId = "alb", toBlockId = "ec2A", flow = ConnectionFlowKind.Request, plainSummary = "The pass calls the ticket to a free cook.", requirement = new ConnectionRequirement { addressNote = "instance registered in the target group", permissionNote = "instance SG allows 80 from the ALB's SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "alb SG"), routeNote = "same VPC; private subnet reachable from the ALB's subnets" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2A2", fromBlockId = "alb", toBlockId = "ec2A2", flow = ConnectionFlowKind.Request, plainSummary = "The new cook is added to the rota and takes tickets.", requirement = new ConnectionRequirement { addressNote = "auto-registered target", permissionNote = "inherits the instance SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "alb SG"), routeNote = "same VPC private subnet" } });
            t.connections.Add(new ConnectionSpec { id = "c_alb_ec2B", fromBlockId = "alb", toBlockId = "ec2B", flow = ConnectionFlowKind.Request, plainSummary = "Tickets also go to the cook on line B.", requirement = new ConnectionRequirement { addressNote = "instance registered in the target group", permissionNote = "instance SG allows 80 from the ALB's SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "80", "alb SG"), routeNote = "same VPC; private subnet in AZ B" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2A_rds", fromBlockId = "ec2A", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The cook fetches ingredients from the pantry.", requirement = new ConnectionRequirement { addressNote = "DB endpoint app-db.abc.eu-west-1.rds.amazonaws.com:5432", permissionNote = "DB SG allows 5432 from the web SG; instance wears a role to read the DB secret", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "web SG"), iam = new IamGrant("web-reads-db-secret", "secretsmanager:GetSecretValue"), routeNote = "same VPC, private subnets" } });
            t.connections.Add(new ConnectionSpec { id = "c_ec2B_rds", fromBlockId = "ec2B", toBlockId = "rdsPrimary", flow = ConnectionFlowKind.Data, plainSummary = "The cook on line B uses the same pantry.", requirement = new ConnectionRequirement { addressNote = "same DB endpoint", permissionNote = "DB SG allows 5432 from the web SG", securityGroup = new SecurityGroupRule("inbound", "TCP", "5432", "web SG"), routeNote = "cross-AZ within the VPC" } });
            t.connections.Add(new ConnectionSpec { id = "c_rds_sync", fromBlockId = "rdsPrimary", toBlockId = "rdsStandby", flow = ConnectionFlowKind.Replication, plainSummary = "The pantry keeps the backup pantry in lockstep.", requirement = new ConnectionRequirement { addressNote = "internal Multi-AZ replication", permissionNote = "managed by RDS", routeNote = "cross-AZ within the VPC" } });

            // ---------- The 9-stage journey. narration = AWS; storyNarration = kitchen. ----------
            t.stages.Add(new StageSpec { index = 0, title = "One cook, one line", focusBlockId = "singleServer", animation = StageAnimation.Overload,
                narration = "A single EC2 instance serves every request. It copes with light traffic, but a spike — or a hardware failure — takes the whole app down. There is no redundancy.",
                storyNarration = "It's opening night with one cook doing everything: taking orders, cooking, plating. A short queue is fine, but the dinner rush hits and tickets pile up faster than one pair of hands can clear. Service grinds to a halt.",
                concept = "One of anything is a single point of failure.", visibleBlockIds = Ids("user", "singleServer"), visibleConnectionIds = Ids("c_user_server") });
            t.stages.Add(new StageSpec { index = 1, title = "Two kitchens", focusBlockId = "region",
                narration = "Start with a Region split into Availability Zones — isolated data centres with independent power and networking. Designing across two AZs lets the app survive losing one.",
                storyNarration = "Give yourself two kitchens in two parts of the building, each on its own power and water. If a pipe bursts in one, the other keeps cooking.",
                concept = "Spread across AZs so losing one doesn't take you down.", visibleBlockIds = Ids("region", "azA", "azB") });
            t.stages.Add(new StageSpec { index = 2, title = "Front and back of house", focusBlockId = "vpc",
                narration = "Create a VPC (10.0.0.0/16) — your private network. Carve it into subnets: public subnets with a route to the internet gateway, and private subnets without one.",
                storyNarration = "Lay out the restaurant: a front of house the public can enter, and a back of house only staff reach. Deliveries come through a single service door.",
                concept = "Public vs private = whether there's a route in from the internet.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw") });
            t.stages.Add(new StageSpec { index = 3, title = "Cooks on the line", focusBlockId = "ec2A",
                narration = "Place the EC2 web servers in private subnets. They have no inbound route from the internet; all traffic must arrive through a public-facing entry point.",
                storyNarration = "Put your cooks on the line in the back — out of the dining room. Guests never walk into the kitchen; everything goes through the front.",
                concept = "Keep app servers private; expose only the entry point.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B") });
            t.stages.Add(new StageSpec { index = 4, title = "The pass", focusBlockId = "alb", animation = StageAnimation.Pulse, animationConnectionId = "c_alb_ec2A",
                narration = "Add an Application Load Balancer in the public subnets. It receives every request and forwards it to a healthy target, using health checks to stop routing to instances that fail.",
                storyNarration = "Add a pass with an expediter. Every order lands at the pass, and the expediter calls it to whichever cook is free — and stops calling a cook who has stepped off the line.",
                concept = "The load balancer spreads load and routes around failures.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B") });
            t.stages.Add(new StageSpec { index = 5, title = "Call in more cooks", focusBlockId = "asg", animation = StageAnimation.Spike,
                narration = "Put the instances in an Auto Scaling group. It launches more instances when demand rises and removes them when it falls, so capacity tracks load and you don't pay for idle servers.",
                storyNarration = "On a rush, the brigade pulls in extra cooks; when it's quiet they clock off. Watch a new cook step onto the line as tickets pile up — you never run out of hands, and don't pay idle ones.",
                concept = "Capacity follows demand, automatically.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2") });
            t.stages.Add(new StageSpec { index = 6, title = "The pantry", focusBlockId = "rdsPrimary", animation = StageAnimation.Pulse, animationConnectionId = "c_ec2A_rds",
                narration = "Add a Multi-AZ RDS database. A synchronous standby is kept in the second AZ; if the primary's AZ fails, RDS promotes the standby automatically with no data loss.",
                storyNarration = "Cooks need one shared pantry — the single source of ingredients and recipes. Keep the main pantry in one kitchen and a stocked backup in the other, restocked in lockstep, so if one kitchen floods the other still has everything.",
                concept = "Multi-AZ database = a hot backup that fails over automatically.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby"), visibleConnectionIds = Ids("c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 7, title = "Host stand & grab-and-go", focusBlockId = "route53", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_ec2A_rds"),
                narration = "Front the app with Route 53 for DNS and CloudFront for edge caching. A request flows: client -> Route 53 -> CloudFront -> ALB -> EC2 -> RDS.",
                storyNarration = "Help guests arriving from afar: the host stand points each one the right way, and a grab-and-go counter by the door serves popular dishes instantly. Follow one order: guest -> host -> grab-and-go -> pass -> cook -> pantry.",
                concept = "Point people with DNS; serve them locally with a CDN.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });
            t.stages.Add(new StageSpec { index = 8, title = "Lose a kitchen, keep serving", focusBlockId = "azA", animation = StageAnimation.Failover,
                narration = "Simulate the failure: Availability Zone A goes down, taking its instance and the RDS primary. The ALB routes to AZ B and RDS fails over to the standby — the app stays available.",
                storyNarration = "Now the disaster. Kitchen A floods — its cook and the main pantry are gone. But the expediter sends every ticket to Kitchen B, and the backup pantry takes over. Service never stops. That's a kitchen that survives a bad night.",
                concept = "High availability = survive losing a whole AZ, with nobody left waiting.", visibleBlockIds = Ids("region", "azA", "azB", "vpc", "pubA", "pubB", "privA", "privB", "igw", "ec2A", "ec2B", "alb", "asg", "ec2A2", "rdsPrimary", "rdsStandby", "cloudfront", "route53", "user"), visibleConnectionIds = Ids("c_user_r53", "c_r53_cf", "c_cf_alb", "c_alb_ec2A", "c_alb_ec2B", "c_alb_ec2A2", "c_ec2A_rds", "c_ec2B_rds", "c_rds_sync") });

            // ---------- Assessment ----------
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Your VPC is 10.0.0.0/16. Which is a valid, correctly-sized subnet inside it?", options = new[] { "10.0.1.0/24", "192.168.1.0/24", "10.0.0.0/8", "11.0.0.0/24" }, correctIndices = new[] { 0 }, explanation = "A subnet must sit inside the VPC's range and be smaller. 10.0.1.0/24 is inside 10.0.0.0/16. A /8 is bigger than a /16, and the other ranges are outside the VPC." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why are the EC2 web servers placed in private subnets?", options = new[] { "So nothing on the internet can reach them directly", "Because private subnets are faster", "Because private subnets are cheaper", "So they don't need a load balancer" }, correctIndices = new[] { 0 }, explanation = "Private subnets have no inbound route from the internet; traffic must arrive via the public-facing load balancer." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.MultiChoice, prompt = "The app must survive one Availability Zone failing. Which TWO are required? (pick two)", options = new[] { "Instances in at least two AZs behind the load balancer", "A Multi-AZ RDS database", "One larger EC2 instance", "Store everything on one instance's local disk" }, correctIndices = new[] { 0, 1 }, explanation = "Surviving an AZ outage needs redundancy across AZs for both compute (multiple AZs behind the ALB) and data (Multi-AZ RDS)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "What does RDS Multi-AZ primarily give you?", options = new[] { "Automatic failover to a standby for high availability", "More read throughput", "Lower storage cost", "A global content cache" }, correctIndices = new[] { 0 }, explanation = "Multi-AZ provides availability via a synchronous standby and automatic failover — not extra read capacity (that's read replicas)." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "How does the load balancer avoid sending requests to a broken instance?", options = new[] { "Health checks — it stops routing to targets that fail them", "It restarts the instance", "It serves a cached response", "It switches to a bigger instance" }, correctIndices = new[] { 0 }, explanation = "The ALB continuously health-checks its targets and only routes to healthy ones." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "Users get no response, yet every instance is healthy. The load balancer was placed in the PRIVATE subnets. Tap the component in the scene that must move to the public subnets to fix this.", tapTargetBlockId = "alb", explanation = "The load balancer must sit in public subnets (with a route to the internet gateway) so internet users can reach it. The instances stay private behind it." });

            return t;
        }

        private static TopicSpec BuildStorage()
        {
            var t = new TopicSpec
            {
                id = "store-serve-content",
                title = "Store & Serve Content",
                examDomain = "Design High-Performing Architectures",
                summary = "Keep every file safe in the larder, serve it fast from the counter, and stash cold stock cheaply.",
                sceneryStyle = StorySceneryStyle.OpenFloor
            };

            t.blocks.Add(new BlockSpec { id = "user", kind = AwsBlockKind.User, displayName = "Global user", category = ServiceCategory.Generic, position = new Vector3(-8f, 0.7f, 0f), storyPosition = new Vector3(-8f, 0.7f, 0f), storyName = "Customer", plainSummary = "A person requesting a file, image or page.", realSummary = "Client HTTPS request for an object." });
            t.blocks.Add(new BlockSpec { id = "cf", kind = AwsBlockKind.CloudFront, displayName = "CloudFront", category = ServiceCategory.Edge, position = new Vector3(-3f, 0.7f, 0f), storyPosition = new Vector3(-3f, 0.7f, 0f), storyName = "Grab-and-go", endpoint = "d111abcdef.cloudfront.net", plainSummary = "Caches objects at edge locations near each user.", realSummary = "CloudFront distribution; origin = the S3 bucket." });
            t.blocks.Add(new BlockSpec { id = "s3", kind = AwsBlockKind.S3Bucket, displayName = "S3 bucket", category = ServiceCategory.Storage, position = new Vector3(1.5f, 0.7f, 0f), storyPosition = new Vector3(1.5f, 0.7f, 0f), storyName = "The larder", endpoint = "my-app-assets.s3.amazonaws.com", arn = new ArnInfo("s3", "", "", "my-app-assets"), plainSummary = "Virtually unlimited object storage; keeps copies across AZs.", realSummary = "S3 bucket; 11 nines of durability, objects replicated across multiple AZs in the Region." });
            t.blocks.Add(new BlockSpec { id = "glacier", kind = AwsBlockKind.GlacierVault, displayName = "S3 Glacier", category = ServiceCategory.Storage, position = new Vector3(5f, 0.7f, 0f), storyPosition = new Vector3(5f, 0.7f, 0f), storyName = "Cold room", plainSummary = "Cheap archival storage for data you rarely touch.", realSummary = "S3 Glacier storage class; very low cost, retrieval in minutes to hours." });

            t.connections.Add(new ConnectionSpec { id = "c_user_s3", fromBlockId = "user", toBlockId = "s3", flow = ConnectionFlowKind.Request, plainSummary = "The customer fetches a file straight from the larder.", requirement = new ConnectionRequirement { addressNote = "the bucket / object URL", permissionNote = "bucket policy allows the read", routeNote = "over the internet to the S3 endpoint" } });
            t.connections.Add(new ConnectionSpec { id = "c_user_cf", fromBlockId = "user", toBlockId = "cf", flow = ConnectionFlowKind.Request, plainSummary = "The customer asks the nearest grab-and-go counter.", requirement = new ConnectionRequirement { addressNote = "the CloudFront domain", permissionNote = "public", routeNote = "served from the nearest edge location" } });
            t.connections.Add(new ConnectionSpec { id = "c_cf_s3", fromBlockId = "cf", toBlockId = "s3", flow = ConnectionFlowKind.Data, plainSummary = "On a cache miss, the counter fetches from the larder.", requirement = new ConnectionRequirement { addressNote = "the S3 origin", permissionNote = "Origin Access Control lets only this distribution read the bucket", routeNote = "CloudFront origin fetch" } });
            t.connections.Add(new ConnectionSpec { id = "c_s3_glacier", fromBlockId = "s3", toBlockId = "glacier", flow = ConnectionFlowKind.Data, plainSummary = "Old stock is moved into the deep cold room.", requirement = new ConnectionRequirement { addressNote = "same object, colder storage class", permissionNote = "managed by the lifecycle rule", routeNote = "S3 lifecycle transition" } });

            t.stages.Add(new StageSpec { index = 0, title = "Into the larder (S3)", focusBlockId = "s3", animation = StageAnimation.Pulse, animationConnectionId = "c_user_s3",
                narration = "Store your files and images in Amazon S3 — virtually unlimited object storage that automatically keeps redundant copies across multiple Availability Zones. No disks to manage, and 11 nines of durability.",
                storyNarration = "Move all your stock into a vast larder with endless shelves. The larder quietly keeps copies on several shelves, so if one collapses you lose nothing.",
                concept = "S3 = durable, managed object storage (copies kept across AZs).", visibleBlockIds = Ids("user", "s3"), visibleConnectionIds = Ids("c_user_s3") });
            t.stages.Add(new StageSpec { index = 1, title = "Serve it fast (CloudFront)", focusBlockId = "cf", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_user_cf", "c_cf_s3"),
                narration = "Put CloudFront in front of S3. It caches objects at edge locations near each user, so most requests are served locally — faster for users, and far less load on the origin.",
                storyNarration = "Set up grab-and-go counters near the diners, stocked with the popular dishes. Most guests are served on the spot, with no trip back to the larder.",
                concept = "A CDN caches near users — lower latency and less origin load.", visibleBlockIds = Ids("user", "cf", "s3"), visibleConnectionIds = Ids("c_user_cf", "c_cf_s3") });
            t.stages.Add(new StageSpec { index = 2, title = "Cold storage (Glacier)", focusBlockId = "glacier", animation = StageAnimation.Pulse, animationConnectionId = "c_s3_glacier",
                narration = "Most objects go cold over time. A lifecycle rule moves rarely-accessed data to S3 Glacier — far cheaper to store, retrieved in minutes to hours when you actually need it.",
                storyNarration = "Rarely-touched stock shouldn't hog prime shelf space. Move it to the deep cold room — dirt cheap to keep, just slower to fetch when an order finally comes in.",
                concept = "Lifecycle to a colder class (Glacier) cuts cost for cold data.", visibleBlockIds = Ids("user", "cf", "s3", "glacier"), visibleConnectionIds = Ids("c_user_cf", "c_cf_s3", "c_s3_glacier") });
            t.stages.Add(new StageSpec { index = 3, title = "Fast, durable, cheap", focusBlockId = "s3", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_user_cf", "c_cf_s3"),
                narration = "A file goes viral. CloudFront absorbs the surge at the edge, S3 serves any misses durably, and cold data sits cheaply in Glacier — you scaled to a global spike with no servers to manage.",
                storyNarration = "A dish goes viral. The grab-and-go counters handle the crowd, the larder never runs dry, and the cold room keeps the bills down. The kitchen barely noticed the rush.",
                concept = "S3 + CloudFront scale content globally — durable and cheap, no servers.", visibleBlockIds = Ids("user", "cf", "s3", "glacier"), visibleConnectionIds = Ids("c_user_cf", "c_cf_s3", "c_s3_glacier") });

            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "What does Amazon S3 give you?", options = new[] { "Durable, virtually unlimited object storage with no servers to manage", "A managed relational database", "A virtual server you patch", "A load balancer" }, correctIndices = new[] { 0 }, explanation = "S3 is managed object storage; it stores redundant copies across AZs for durability and scales without you managing disks." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why put CloudFront in front of S3?", options = new[] { "Cache content at edge locations near users — lower latency and origin load", "To make S3 durable", "To store relational data", "To replace IAM" }, correctIndices = new[] { 0 }, explanation = "CloudFront is a CDN: it serves cached copies near users and cuts requests to the S3 origin." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "You have data you rarely access but must keep cheaply. What fits?", options = new[] { "A lifecycle rule moving it to S3 Glacier", "Delete it", "Keep it on an EC2 disk", "Cache it in CloudFront forever" }, correctIndices = new[] { 0 }, explanation = "Lifecycle rules transition cold objects to cheaper classes such as Glacier." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Where does S3's durability come from?", options = new[] { "It automatically stores redundant copies across multiple Availability Zones", "You configure RAID yourself", "A single disk with nightly backups", "CloudFront edge caches" }, correctIndices = new[] { 0 }, explanation = "S3 redundantly stores each object across multiple AZs within the Region." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "Downloads are slow for users worldwide and your S3 origin is overloaded. Tap the component to add in front of S3.", tapTargetBlockId = "cf", explanation = "CloudFront caches content at edge locations near users, cutting latency and offloading the S3 origin." });

            return t;
        }

        private static TopicSpec BuildIam()
        {
            var t = new TopicSpec
            {
                id = "secure-access-iam",
                title = "Secure Access with IAM",
                examDomain = "Design Secure Architectures",
                summary = "Hand out the right keys: individual identities, least privilege, temporary badges, and a second lock.",
                sceneryStyle = StorySceneryStyle.OpenFloor
            };

            t.blocks.Add(new BlockSpec { id = "staff", kind = AwsBlockKind.User, displayName = "Person / app", category = ServiceCategory.Generic, position = new Vector3(-7f, 0.7f, 0f), storyPosition = new Vector3(-7f, 0.7f, 0f), storyName = "Staff member", plainSummary = "Someone (or something) that needs access.", realSummary = "An IAM identity: a user, a federated principal, or a role." });
            t.blocks.Add(new BlockSpec { id = "iam", kind = AwsBlockKind.IamService, displayName = "IAM", category = ServiceCategory.Security, position = new Vector3(-2f, 0.7f, 0f), storyPosition = new Vector3(-2f, 0.7f, 0f), storyName = "Security desk", plainSummary = "Issues identities and decides who can do what.", realSummary = "IAM: users, roles, and policies that allow or deny actions on resources." });
            t.blocks.Add(new BlockSpec { id = "stockroom", kind = AwsBlockKind.S3Bucket, displayName = "Assets bucket", category = ServiceCategory.Storage, position = new Vector3(2.5f, 0.7f, -1.6f), storyPosition = new Vector3(2.5f, 0.7f, -1.6f), storyName = "Stockroom", arn = new ArnInfo("s3", "", "", "app-assets"), plainSummary = "A resource this identity is allowed to use.", realSummary = "An S3 bucket the identity's policy permits." });
            t.blocks.Add(new BlockSpec { id = "safe", kind = AwsBlockKind.S3Bucket, displayName = "Payroll bucket", category = ServiceCategory.Storage, position = new Vector3(2.5f, 0.7f, 1.6f), storyPosition = new Vector3(2.5f, 0.7f, 1.6f), storyName = "Payroll safe", storyProp = "coldroom", arn = new ArnInfo("s3", "", "", "payroll"), plainSummary = "A resource this identity must NOT use.", realSummary = "An S3 bucket the policy doesn't grant — least privilege keeps it off-limits." });

            t.connections.Add(new ConnectionSpec { id = "c_staff_iam", fromBlockId = "staff", toBlockId = "iam", flow = ConnectionFlowKind.Request, plainSummary = "Collect a badge from the security desk.", requirement = new ConnectionRequirement { addressNote = "the identity (user or role)", permissionNote = "authenticated (password/keys, ideally + MFA)", routeNote = "AWS sign-in / STS" } });
            t.connections.Add(new ConnectionSpec { id = "c_staff_stock", fromBlockId = "staff", toBlockId = "stockroom", flow = ConnectionFlowKind.Request, plainSummary = "The badge opens the stockroom — the policy allows it.", requirement = new ConnectionRequirement { addressNote = "the bucket ARN", permissionNote = "the attached policy grants s3:GetObject on this bucket", iam = new IamGrant("assets-reader", "s3:GetObject on app-assets"), routeNote = "evaluated by IAM on every request" } });

            t.stages.Add(new StageSpec { index = 0, title = "Lock away the master key", focusBlockId = "iam", animation = StageAnimation.Pulse, animationConnectionId = "c_staff_iam",
                narration = "The account root user can do anything and can't be restricted. Using it day-to-day is dangerous — one leak exposes everything. Lock it away behind MFA and create individual IAM identities for real work.",
                storyNarration = "There's one master key that opens every door in the building. If a manager carries it around and loses it, you're finished. Lock it in the safe and give people their own keys.",
                concept = "Never use the account root user for daily work.", visibleBlockIds = Ids("staff", "iam"), visibleConnectionIds = Ids("c_staff_iam") });
            t.stages.Add(new StageSpec { index = 1, title = "Everyone gets their own key", focusBlockId = "staff",
                narration = "Give each person and application its own IAM identity. Now every action is traceable to someone, and you can rotate or revoke one set of credentials without disturbing the rest.",
                storyNarration = "Issue each staff member their own keycard from the security desk. You can see who opened what, and cancel one card without re-keying the whole building.",
                concept = "Individual identities = traceable, independently revocable access.", visibleBlockIds = Ids("staff", "iam", "stockroom"), visibleConnectionIds = Ids("c_staff_iam", "c_staff_stock") });
            t.stages.Add(new StageSpec { index = 2, title = "Least privilege", focusBlockId = "safe", animation = StageAnimation.Pulse, animationConnectionId = "c_staff_stock",
                narration = "Attach policies that grant only what each identity needs. The assets role can read the assets bucket but not the payroll bucket. Start closed, and add permissions deliberately.",
                storyNarration = "The badge opens the stockroom — but NOT the payroll safe. Each badge opens only the doors that job needs, and nothing more.",
                concept = "Least privilege: grant only the permissions actually needed.", visibleBlockIds = Ids("staff", "iam", "stockroom", "safe"), visibleConnectionIds = Ids("c_staff_iam", "c_staff_stock") });
            t.stages.Add(new StageSpec { index = 3, title = "Roles, not long-lived keys", focusBlockId = "iam", animation = StageAnimation.Pulse, animationConnectionId = "c_staff_iam",
                narration = "For temporary access and for services, use IAM roles — short-lived credentials assumed on demand — instead of long-lived access keys. An EC2 instance assumes a role to reach S3; no secrets are baked into the app.",
                storyNarration = "Don't hand out permanent keys. Issue a shift badge that expires at the end of the shift — and even the delivery van (a service) gets a temporary badge, never the master key.",
                concept = "Prefer roles (temporary credentials) over long-lived access keys.", visibleBlockIds = Ids("staff", "iam", "stockroom", "safe"), visibleConnectionIds = Ids("c_staff_iam", "c_staff_stock") });
            t.stages.Add(new StageSpec { index = 4, title = "Add a second lock (MFA)", focusBlockId = "staff",
                narration = "Require MFA for privileged users and sensitive actions. Even if a password leaks, an attacker can't get in without the second factor.",
                storyNarration = "Put a second lock on the important doors: the keycard AND a code from the staff member's phone. A stolen card alone won't open it.",
                concept = "MFA stops a stolen password from being enough.", visibleBlockIds = Ids("staff", "iam", "stockroom", "safe"), visibleConnectionIds = Ids("c_staff_iam", "c_staff_stock") });

            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Should you use the AWS account root user for day-to-day work?", options = new[] { "No — lock it away with MFA and use individual IAM identities", "Yes, it's simplest", "Only on weekdays", "Only for read-only tasks" }, correctIndices = new[] { 0 }, explanation = "Root is unrestricted and a single point of compromise. Secure it with MFA and use least-privilege IAM identities instead." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "What does 'least privilege' mean?", options = new[] { "Grant only the permissions an identity actually needs", "Give everyone admin to avoid blockers", "Turn off logging", "Share one user across the team" }, correctIndices = new[] { 0 }, explanation = "Start closed and grant only the specific actions and resources required." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "An EC2 instance needs to read an S3 bucket. Best practice?", options = new[] { "Attach an IAM role the instance assumes (temporary credentials)", "Hard-code an access key in the app", "Use the root user", "Make the bucket public" }, correctIndices = new[] { 0 }, explanation = "Roles provide rotating, short-lived credentials with no secrets stored in the app." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why require MFA?", options = new[] { "A stolen password alone can't grant access", "It makes logins faster", "It replaces IAM policies", "It encrypts data at rest" }, correctIndices = new[] { 0 }, explanation = "MFA adds a second factor, so a leaked password isn't enough on its own." });

            return t;
        }

        private static TopicSpec BuildNetworking()
        {
            var t = new TopicSpec
            {
                id = "network-boundaries-vpc",
                title = "Network Boundaries",
                examDomain = "Design Secure Architectures",
                summary = "Keep servers off the street: private rooms, a bouncer on every door, and one guarded entrance.",
                sceneryStyle = StorySceneryStyle.OpenFloor
            };

            t.blocks.Add(new BlockSpec { id = "admin", kind = AwsBlockKind.User, displayName = "Admin", category = ServiceCategory.Generic, position = new Vector3(-8f, 0.7f, 0f), storyPosition = new Vector3(-8f, 0.7f, 0f), storyName = "Admin", plainSummary = "An operator who needs to manage the server.", realSummary = "An administrator connecting from the internet." });
            t.blocks.Add(new BlockSpec { id = "igw", kind = AwsBlockKind.InternetGateway, displayName = "Internet gateway", category = ServiceCategory.Networking, position = new Vector3(-4.5f, 0.7f, 0f), storyPosition = new Vector3(-4.5f, 0.7f, 0f), storyName = "Front door", plainSummary = "The only route between the VPC and the internet.", realSummary = "Internet gateway; only public subnets route to it." });
            t.blocks.Add(new BlockSpec { id = "bastion", kind = AwsBlockKind.BastionHost, displayName = "Bastion host", category = ServiceCategory.Compute, position = new Vector3(-1.5f, 0.7f, 0f), storyPosition = new Vector3(-1.5f, 0.7f, 0f), storyName = "Guard post", plainSummary = "The one hardened, audited way in to private servers.", realSummary = "Bastion host in a public subnet (or use SSM Session Manager instead)." });
            t.blocks.Add(new BlockSpec { id = "sg", kind = AwsBlockKind.SecurityGroup, displayName = "Security group", category = ServiceCategory.Security, position = new Vector3(2f, 0.7f, 0f), storyPosition = new Vector3(2f, 0.7f, 0f), storyName = "Bouncer", plainSummary = "Allows only specific traffic to the server.", realSummary = "Stateful, instance-level firewall; deny by default, allow named sources and ports." });
            t.blocks.Add(new BlockSpec { id = "web", kind = AwsBlockKind.Ec2Instance, displayName = "Web server", category = ServiceCategory.Compute, position = new Vector3(5f, 0.7f, 0f), storyPosition = new Vector3(5f, 0.7f, 0f), storyName = "Back-of-house server", ports = new[] { "443" }, plainSummary = "The server doing the work, kept private.", realSummary = "EC2 in a private subnet; reachable only via the load balancer/bastion per its security group." });

            t.connections.Add(new ConnectionSpec { id = "c_admin_web", fromBlockId = "admin", toBlockId = "web", flow = ConnectionFlowKind.Request, plainSummary = "Anyone on the internet reaching the server directly.", requirement = new ConnectionRequirement { addressNote = "the server's public IP", permissionNote = "wide-open SG (22 from 0.0.0.0/0) — dangerous", securityGroup = new SecurityGroupRule("inbound", "TCP", "22", "0.0.0.0/0"), routeNote = "public subnet, public IP" } });
            t.connections.Add(new ConnectionSpec { id = "c_admin_bastion", fromBlockId = "admin", toBlockId = "bastion", flow = ConnectionFlowKind.Request, plainSummary = "Admins enter only through the guarded post.", requirement = new ConnectionRequirement { addressNote = "the bastion's address", permissionNote = "bastion SG allows the admin source only", securityGroup = new SecurityGroupRule("inbound", "TCP", "22", "admin office IP"), routeNote = "public subnet" } });
            t.connections.Add(new ConnectionSpec { id = "c_bastion_web", fromBlockId = "bastion", toBlockId = "web", flow = ConnectionFlowKind.Network, plainSummary = "From the guard post, reach the private server.", requirement = new ConnectionRequirement { addressNote = "the server's private IP", permissionNote = "server SG allows the bastion's SG only", securityGroup = new SecurityGroupRule("inbound", "TCP", "22", "bastion SG"), routeNote = "private subnet, internal" } });
            t.connections.Add(new ConnectionSpec { id = "c_sg_web", fromBlockId = "sg", toBlockId = "web", flow = ConnectionFlowKind.Network, plainSummary = "The bouncer controls who reaches the server's door.", requirement = new ConnectionRequirement { addressNote = "applied to the instance", permissionNote = "allow 443 from the load balancer; deny the rest", securityGroup = new SecurityGroupRule("inbound", "TCP", "443", "load-balancer SG"), routeNote = "evaluated on every packet to the instance" } });

            t.stages.Add(new StageSpec { index = 0, title = "Don't leave the door open", focusBlockId = "web", animation = StageAnimation.Overload, animationConnectionId = "c_admin_web",
                narration = "A server with a public IP and SSH/RDP open to 0.0.0.0/0 is found and attacked within minutes. Direct, unrestricted exposure is the most common mistake.",
                storyNarration = "Leaving the kitchen's street door propped open means anyone can wander straight in — and bots rattle the handle around the clock.",
                concept = "Don't expose servers directly to the whole internet.", visibleBlockIds = Ids("admin", "web"), visibleConnectionIds = Ids("c_admin_web") });
            t.stages.Add(new StageSpec { index = 1, title = "Move it to a private room", focusBlockId = "web",
                narration = "Place servers in private subnets — there is no route from the internet to them. Only what you deliberately put in a public subnet (a load balancer, a bastion) is reachable.",
                storyNarration = "Move the kitchen to the back of house. There simply is no door from the street to it — you come through the front and get let through.",
                concept = "Private subnets have no inbound route from the internet.", visibleBlockIds = Ids("admin", "igw", "web") });
            t.stages.Add(new StageSpec { index = 2, title = "A bouncer on the door", focusBlockId = "sg", animation = StageAnimation.Pulse, animationConnectionId = "c_sg_web",
                narration = "A security group is a stateful firewall on the instance: allow only the ports and sources you need (e.g. 443 from the load balancer's group); everything else is denied by default. A NACL adds a coarser, stateless check at the subnet edge.",
                storyNarration = "Post a bouncer at the door with a guest list: only the front desk's people get in, on the one door that matters. Everyone else is turned away.",
                concept = "Security groups: stateful, instance-level allow-lists (deny by default).", visibleBlockIds = Ids("admin", "igw", "sg", "web"), visibleConnectionIds = Ids("c_sg_web") });
            t.stages.Add(new StageSpec { index = 3, title = "One guarded entrance", focusBlockId = "bastion", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_admin_bastion", "c_bastion_web"),
                narration = "Admins shouldn't open SSH to the world. Reach private servers through a single hardened, audited entry point — a bastion host, or better, SSM Session Manager with no open inbound ports at all.",
                storyNarration = "Staff don't each get a street door. They check in at one guarded post, and only from there can they step into the back of house.",
                concept = "One hardened, audited entrance beats exposing every server.", visibleBlockIds = Ids("admin", "igw", "bastion", "sg", "web"), visibleConnectionIds = Ids("c_admin_bastion", "c_bastion_web", "c_sg_web") });

            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "A web server should accept traffic only from the load balancer. Best tool?", options = new[] { "A security group allowing 443 from the load balancer's group", "Give the server a public IP", "A NAT gateway", "An S3 bucket policy" }, correctIndices = new[] { 0 }, explanation = "Security groups are stateful, instance-level firewalls; allow only the needed port from the specific source group." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Security groups are…", options = new[] { "Stateful firewalls at the instance level", "Stateless and only at the subnet level", "A DNS service", "A storage class" }, correctIndices = new[] { 0 }, explanation = "Security groups are stateful and instance-level; NACLs are the stateless, subnet-level control." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "How should admins reach servers in private subnets?", options = new[] { "Via a bastion host or SSM Session Manager", "Open SSH to 0.0.0.0/0 on every server", "Give every server a public IP", "Disable the security group" }, correctIndices = new[] { 0 }, explanation = "A single hardened, audited entry point minimises exposure; SSM needs no open inbound ports at all." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "This server is exposed to the whole internet on SSH. Tap the component to route admin access through instead.", tapTargetBlockId = "bastion", explanation = "A bastion host (or SSM) is the single guarded door to private servers; don't take SSH from the world on each server." });

            return t;
        }

        private static TopicSpec BuildMessaging()
        {
            var t = new TopicSpec
            {
                id = "decouple-with-queue-sqs",
                title = "Decouple with a Queue",
                examDomain = "Design Resilient Architectures",
                summary = "Stop the waiter waiting on the cook: a ticket rail buffers orders so neither side ever stalls.",
                sceneryStyle = StorySceneryStyle.KitchenLines
            };

            t.blocks.Add(new BlockSpec { id = "waiter", kind = AwsBlockKind.Ec2Instance, displayName = "Producer", category = ServiceCategory.Compute, position = new Vector3(-6f, 0.7f, 0f), storyPosition = new Vector3(-6f, 0.7f, 0f), storyName = "Waiter", storyProp = "customer", plainSummary = "Creates work (sends messages).", realSummary = "A producer app that sends messages to the queue." });
            t.blocks.Add(new BlockSpec { id = "queue", kind = AwsBlockKind.SqsQueue, displayName = "SQS queue", category = ServiceCategory.Generic, position = new Vector3(-1f, 0.7f, 0f), storyPosition = new Vector3(-1f, 0.7f, 0f), storyName = "Ticket rail", endpoint = "https://sqs.eu-west-1.amazonaws.com/123/orders", plainSummary = "Holds messages until a consumer is ready.", realSummary = "An SQS queue; messages wait, are processed at-least-once, then deleted." });
            t.blocks.Add(new BlockSpec { id = "cookA", kind = AwsBlockKind.Ec2Instance, displayName = "Consumer", category = ServiceCategory.Compute, position = new Vector3(3f, 0.7f, -1.6f), storyPosition = new Vector3(3f, 0.7f, -1.6f), storyName = "Cook", ports = new[] { "80" }, plainSummary = "Does the work (processes messages).", realSummary = "A consumer that polls the queue and processes messages." });
            t.blocks.Add(new BlockSpec { id = "cookB", kind = AwsBlockKind.Ec2Instance, displayName = "Consumer (scaled out)", category = ServiceCategory.Compute, position = new Vector3(4.4f, 0.7f, 1.6f), storyPosition = new Vector3(4.4f, 0.7f, 1.6f), storyName = "Extra cook", ports = new[] { "80" }, plainSummary = "An extra consumer added to clear a backlog.", realSummary = "A consumer added by scaling on queue depth." });
            t.blocks.Add(new BlockSpec { id = "dlq", kind = AwsBlockKind.SqsQueue, displayName = "Dead-letter queue", category = ServiceCategory.Generic, position = new Vector3(3f, 0.7f, 3.2f), storyPosition = new Vector3(3f, 0.7f, 3.2f), storyName = "Lost-tickets bin", plainSummary = "Holds messages that keep failing, for review.", realSummary = "Dead-letter queue; messages move here after N failed receives." });

            t.connections.Add(new ConnectionSpec { id = "c_waiter_cook", fromBlockId = "waiter", toBlockId = "cookA", flow = ConnectionFlowKind.Request, plainSummary = "The waiter hands the order straight to the cook and waits.", requirement = new ConnectionRequirement { addressNote = "the consumer's address", permissionNote = "the consumer must be up right now", routeNote = "synchronous call" } });
            t.connections.Add(new ConnectionSpec { id = "c_waiter_queue", fromBlockId = "waiter", toBlockId = "queue", flow = ConnectionFlowKind.Data, plainSummary = "The waiter clips the ticket to the rail and moves on.", requirement = new ConnectionRequirement { addressNote = "the queue URL", permissionNote = "sqs:SendMessage", routeNote = "fire-and-forget send" } });
            t.connections.Add(new ConnectionSpec { id = "c_queue_cookA", fromBlockId = "queue", toBlockId = "cookA", flow = ConnectionFlowKind.Data, plainSummary = "A cook pulls the next ticket when free.", requirement = new ConnectionRequirement { addressNote = "the queue URL", permissionNote = "sqs:ReceiveMessage / DeleteMessage", routeNote = "consumer polls" } });
            t.connections.Add(new ConnectionSpec { id = "c_queue_cookB", fromBlockId = "queue", toBlockId = "cookB", flow = ConnectionFlowKind.Data, plainSummary = "Extra cooks pull tickets to clear the backlog.", requirement = new ConnectionRequirement { addressNote = "the same queue", permissionNote = "sqs:ReceiveMessage", routeNote = "more consumers share the load" } });
            t.connections.Add(new ConnectionSpec { id = "c_queue_dlq", fromBlockId = "queue", toBlockId = "dlq", flow = ConnectionFlowKind.Data, plainSummary = "A ticket that keeps failing is set aside in the bin.", requirement = new ConnectionRequirement { addressNote = "the dead-letter queue", permissionNote = "redrive policy after maxReceiveCount", routeNote = "automatic on repeated failures" } });

            t.stages.Add(new StageSpec { index = 0, title = "Stuck at the pass", focusBlockId = "cookA", animation = StageAnimation.Overload, animationConnectionId = "c_waiter_cook",
                narration = "When a producer calls a consumer directly and waits, a slow or failed consumer stalls the producer — and work is lost if the consumer is down. The two are tightly coupled.",
                storyNarration = "The waiter carries each order straight to a cook and waits for it to be taken. If the cook is slammed, the waiter is stuck at the pass and new orders pile up at the door.",
                concept = "Direct coupling: a slow or failed consumer stalls the producer.", visibleBlockIds = Ids("waiter", "cookA"), visibleConnectionIds = Ids("c_waiter_cook") });
            t.stages.Add(new StageSpec { index = 1, title = "Hang a ticket rail", focusBlockId = "queue", animation = StageAnimation.Chain, animationChainConnectionIds = Ids("c_waiter_queue", "c_queue_cookA"),
                narration = "Put an SQS queue between them. The producer sends a message and returns immediately; the consumer polls and processes when ready. Neither waits on the other.",
                storyNarration = "Hang a ticket rail at the pass. The waiter clips the order to the rail and heads back to the floor; cooks pull the next ticket whenever a pair of hands is free.",
                concept = "A queue decouples producer from consumer — neither blocks the other.", visibleBlockIds = Ids("waiter", "queue", "cookA"), visibleConnectionIds = Ids("c_waiter_queue", "c_queue_cookA") });
            t.stages.Add(new StageSpec { index = 2, title = "Absorb the rush", focusBlockId = "cookB", animation = StageAnimation.Spike,
                narration = "During a surge the queue buffers the backlog so nothing is dropped, and you scale consumers on queue depth to work through it.",
                storyNarration = "A rush fills the rail with tickets — none are lost. Call in extra cooks who pull tickets until the rail clears.",
                concept = "A queue buffers spikes; scale consumers on queue depth.", visibleBlockIds = Ids("waiter", "queue", "cookA", "cookB"), visibleConnectionIds = Ids("c_waiter_queue", "c_queue_cookA", "c_queue_cookB") });
            t.stages.Add(new StageSpec { index = 3, title = "Set aside the bad tickets", focusBlockId = "dlq", animation = StageAnimation.Pulse, animationConnectionId = "c_queue_dlq",
                narration = "Configure a dead-letter queue: a message that fails repeatedly is moved aside after N attempts, so one poison message doesn't block the queue. You inspect and fix it later.",
                storyNarration = "A ticket nobody can cook — out of an ingredient — keeps coming back. After a few tries it goes in the lost-tickets bin for the manager, and never jams the rail.",
                concept = "A dead-letter queue isolates poison messages so the queue keeps flowing.", visibleBlockIds = Ids("waiter", "queue", "cookA", "cookB", "dlq"), visibleConnectionIds = Ids("c_waiter_queue", "c_queue_cookA", "c_queue_cookB", "c_queue_dlq") });

            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Why put an SQS queue between a producer and a consumer?", options = new[] { "So a slow or failed consumer doesn't stall the producer, and work isn't lost", "To make the consumer run faster", "To store files cheaply", "To replace IAM" }, correctIndices = new[] { 0 }, explanation = "A queue decouples the two: the producer returns immediately and messages wait safely until consumed." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "Traffic spikes far beyond what consumers can handle. With a queue…", options = new[] { "Messages buffer in the queue; scale consumers to work through the backlog", "Messages are dropped immediately", "The producer crashes", "Nothing can be done" }, correctIndices = new[] { 0 }, explanation = "The queue absorbs the spike; scale consumers on queue depth to drain it." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.SingleChoice, prompt = "A message fails processing again and again. Best practice?", options = new[] { "Send it to a dead-letter queue after N attempts for later inspection", "Retry it forever", "Delete the whole queue", "Ignore all failures" }, correctIndices = new[] { 0 }, explanation = "A DLQ isolates poison messages so they don't block healthy ones; you review them separately." });
            t.quiz.questions.Add(new QuestionSpec { kind = QuestionKind.TapToFix, prompt = "The waiter (producer) is stuck waiting on a busy cook. Tap what to add between them so neither stalls.", tapTargetBlockId = "queue", explanation = "An SQS queue buffers messages: the producer sends and returns; consumers process when ready." });

            return t;
        }
    }
}
