import type { Topic } from '@content';

/** Cloud Practitioner (CLF-C02) — the foundational badge. Domains at official
 *  weights: Cloud Concepts 24 · Security & Compliance 30 · Cloud Technology &
 *  Services 34 · Billing, Pricing & Support 12. */

const t = (o: { id: string; title: string; examDomain: string; summary: string; primer: string; quiz: Topic['quiz'] }): Topic =>
  ({ ...o, blocks: [], connections: [], stages: [] });

export const CLF_DOMAIN = {
  concepts: 'Cloud Concepts',
  security: 'Security and Compliance',
  tech: 'Cloud Technology and Services',
  billing: 'Billing, Pricing, and Support',
};

export const CLF_COURSE: { title: string; topics: Topic[] } = {
  title: 'On-Call: Cloud Practitioner Badge (CLF-C02)',
  topics: [
    t({
      id: 'clf-elasticity',
      title: 'Why Cloud: Elasticity',
      examDomain: CLF_DOMAIN.concepts,
      summary: 'Buying servers for the biggest day of the year means paying for them every other day. Elasticity matches capacity to demand, hour by hour.',
      primer: 'The cloud\'s founding trade: CAPITAL expense (buy hardware for the worst case, depreciate it while it idles) becomes VARIABLE expense (rent capacity by the hour as demand arrives). ELASTICITY is the mechanism — capacity grows for the spike and, just as importantly, shrinks back after. That kills the two classic failure modes of guessing: over-provisioning (paying every day for one big day) and under-provisioning (falling over on the day that pays for the year). The headline value propositions to know: stop guessing capacity, trade CapEx for OpEx, and go global in minutes.',
      quiz: [
        { kind: 'single', prompt: 'The core economic shift of cloud computing is:',
          options: ['Cheaper electricity', 'Trading capital expense (buy for peak) for variable expense (pay for use)', 'Free data transfer', 'Faster CPUs'],
          correct: [1], explain: 'CapEx→OpEx: capacity becomes a utility you rent as needed instead of hardware you buy for the worst case.' },
        { kind: 'single', prompt: '"Elasticity" means:',
          options: ['Servers never fail', 'Capacity grows AND shrinks automatically with demand', 'Unlimited free tier', 'Data is replicated'],
          correct: [1], explain: 'Elastic systems scale out for the spike and — just as important — scale back in when it passes.' },
        { kind: 'single', prompt: 'A retailer sized its own datacenter for Black Friday. In the cloud model, the equivalent waste is:',
          options: ['Unavoidable', 'Eliminated — provision for today, scale for the spike, release after', 'Doubled', 'Moved to networking'],
          correct: [1], explain: 'Peak-sizing on-prem means ~360 days of idle metal. Elastic capacity exists only while the spike does.' },
        { kind: 'multi', prompt: 'Which are cloud value propositions? (Pick 2)',
          options: ['Stop guessing capacity', 'Go global in minutes', 'Hardware you can touch', 'Fixed annual costs'],
          correct: [0, 1], explain: 'Capacity on demand and global reach are headline benefits; touchable hardware and fixed costs are the old world.' },
      ],
    }),
    t({
      id: 'clf-regions-azs',
      title: 'Regions & Availability Zones',
      examDomain: CLF_DOMAIN.concepts,
      summary: 'A Region is a place on the map; an Availability Zone is an isolated datacenter cluster inside it. Surviving a bad day means using more than one AZ.',
      primer: 'AWS geography has three layers. A REGION is a place on the map (eu-west-1) — chosen for latency to your users and data-residency law. Inside each Region sit multiple AVAILABILITY ZONES: clusters of datacenters with independent power, cooling, and networking, close enough for millisecond replication but isolated enough that one zone\'s bad night doesn\'t spread. Running in TWO AZs is the basic unit of surviving failure — two servers in ONE zone share a fate. EDGE LOCATIONS are the third layer: hundreds of small caching sites (CloudFront) that speed delivery worldwide; your servers and data still live in Regions.',
      quiz: [
        { kind: 'single', prompt: 'An Availability Zone is best described as:',
          options: ['A country', 'One or more isolated datacenters within a Region, with independent power and networking', 'A billing unit', 'A CDN location'],
          correct: [1], explain: 'AZs are the isolation unit inside a Region — close enough for fast replication, separate enough that one failing doesn\'t take the others.' },
        { kind: 'single', prompt: 'Running your app in two AZs protects you against:',
          options: ['A whole-Region outage', 'The failure of a single datacenter cluster', 'DDoS attacks', 'High AWS bills'],
          correct: [1], explain: 'Multi-AZ survives an AZ failure. A whole-Region event needs a multi-Region strategy.' },
        { kind: 'multi', prompt: 'What commonly drives the choice of Region? (Pick 2)',
          options: ['Latency to your users', 'Data-residency / compliance requirements', 'The Region\'s alphabet position', 'The console color scheme'],
          correct: [0, 1], explain: 'Put data near the users it serves and inside the borders the law requires.' },
        { kind: 'single', prompt: 'Edge locations (CloudFront) differ from Regions because they:',
          options: ['Run EC2 instances', 'Cache content close to users in far more cities than there are Regions', 'Are cheaper Regions', 'Store your database'],
          correct: [1], explain: 'Hundreds of edge sites cache and accelerate; your servers and data still live in Regions.' },
      ],
    }),
    t({
      id: 'clf-shared-responsibility',
      title: 'The Shared Responsibility Model',
      examDomain: CLF_DOMAIN.security,
      summary: 'AWS secures the cloud itself — buildings, hardware, hypervisor. You secure what you put IN it — data, identities, configurations. Confusing the two is how buckets go public.',
      primer: 'The Shared Responsibility Model draws one line: AWS is responsible for security OF the cloud — physical datacenters, hardware, and the virtualization layer (you couldn\'t patch a hypervisor if you wanted to). You are responsible for security IN the cloud — your data, IAM identities and MFA, bucket policies, encryption choices, application code, and (on EC2) the guest operating system you run. Managed services shift more of the stack to AWS, but data and access configuration NEVER stop being yours: a world-readable bucket is always a customer misconfiguration. Support plans change response times, not responsibility.',
      quiz: [
        { kind: 'single', prompt: 'Under shared responsibility, patching the physical hypervisor hosts is:',
          options: ['Your job', 'AWS\'s job — security OF the cloud', 'The auditor\'s job', 'Optional'],
          correct: [1], explain: 'Physical facilities, hardware, and the virtualization layer are AWS\'s side of the line.' },
        { kind: 'single', prompt: 'A world-readable S3 bucket full of customer data is:',
          options: ['An AWS security failure', 'Your responsibility — customer configuration is security IN the cloud', 'Impossible', 'A support-plan issue'],
          correct: [1], explain: 'AWS provides the controls; configuring them (bucket policies, encryption, access) is the customer side.' },
        { kind: 'multi', prompt: 'Which are CUSTOMER responsibilities? (Pick 2)',
          options: ['IAM users, roles, and MFA', 'Encrypting data and classifying it', 'Datacenter badge readers', 'Replacing failed disks'],
          correct: [0, 1], explain: 'Identity and data protection are always yours; physical security and hardware are always AWS\'s.' },
        { kind: 'single', prompt: 'For EC2, patching the GUEST operating system belongs to:',
          options: ['AWS', 'You — the customer manages what runs on the instance', 'Intel', 'Nobody'],
          correct: [1], explain: 'IaaS hands you the OS and up. Managed services shift more of that stack to AWS — one reason to use them.' },
      ],
    }),
    t({
      id: 'clf-account-hygiene',
      title: 'Root Account Hygiene',
      examDomain: CLF_DOMAIN.security,
      summary: 'The root user can do — and lose — everything. Lock it away with MFA, create IAM identities for daily work, and never mint root access keys.',
      primer: 'Every AWS account has a ROOT user that bypasses all policies and can do anything — including close the account. Hygiene rule one: protect root with MFA (a stolen password alone then fails), use it for the handful of account-level tasks that truly require it, and lock it away. Rule two: daily work happens as scoped IAM identities — named users and roles with least-privilege policies, so mistakes are contained and the audit trail shows WHO did what. Rule three: never create root ACCESS KEYS — an unscopeable, unexpiring API skeleton key. IAM roles cover every legitimate automation need.',
      quiz: [
        { kind: 'single', prompt: 'The root user should be used for:',
          options: ['Daily administration', 'Almost nothing — a few account-level tasks, then locked away with MFA', 'CI/CD pipelines', 'Cost reporting'],
          correct: [1], explain: 'Root bypasses all policies and can close the account. Day-to-day work belongs to scoped IAM identities.' },
        { kind: 'single', prompt: 'The single most important protection for the root user is:',
          options: ['A long username', 'Multi-factor authentication', 'Using it often so you remember the password', 'Sharing it with a trusted colleague'],
          correct: [1], explain: 'MFA means a stolen password alone cannot take the account.' },
        { kind: 'single', prompt: 'Root access keys (for CLI/API) should be:',
          options: ['Rotated monthly', 'Never created — delete them if they exist', 'Stored in the team wiki', 'Used only on Fridays'],
          correct: [1], explain: 'A root key is an un-scopeable skeleton key in a text file. IAM roles and users cover every legitimate need.' },
        { kind: 'multi', prompt: 'Good day-one account practices include: (Pick 2)',
          options: ['MFA on root', 'IAM admin user/role for daily work', 'Emailing the root password to the team', 'Disabling CloudTrail to save money'],
          correct: [0, 1], explain: 'Protect root, then stop using it. Sharing credentials and blinding your audit log are the opposite of hygiene.' },
      ],
    }),
    t({
      id: 'clf-core-services',
      title: 'The Core Service Map',
      examDomain: CLF_DOMAIN.tech,
      summary: 'Four workloads, four homes: virtual machines on EC2, objects in S3, managed databases on RDS, and functions on Lambda. Most architectures start here.',
      primer: 'Four primitives cover most starting architectures. EC2: resizable virtual machines — a whole OS you control, for long-lived apps. S3: object storage — things fetched by name over HTTP, eleven nines of durability, no servers (images, backups, static sites). RDS: managed relational databases — real engines with backups, patching, and failover run by AWS; you keep schema and queries. LAMBDA: functions — short event-driven code billed by the millisecond, costing nothing idle. The matching skill is recognizing a workload\'s SHAPE: named objects → S3, always-on process → EC2, transactions and joins → RDS, brief bursts on events → Lambda.',
      quiz: [
        { kind: 'single', prompt: 'Store millions of images, each retrieved by name over HTTP. The natural home is:',
          options: ['EC2 instance disk', 'Amazon S3 — durable object storage', 'RDS', 'CloudWatch'],
          correct: [1], explain: 'Objects by key, eleven nines of durability, no servers: that\'s S3\'s exact job.' },
        { kind: 'single', prompt: 'A relational database WITHOUT managing backups, patching, or failover yourself:',
          options: ['MySQL on EC2', 'Amazon RDS', 'S3', 'An on-prem server'],
          correct: [1], explain: 'RDS is the managed option — same engines, but AWS runs the undifferentiated operations.' },
        { kind: 'single', prompt: 'Run code for 200ms whenever a file arrives, with no servers to manage:',
          options: ['EC2 Auto Scaling', 'AWS Lambda', 'Amazon Lightsail', 'ECS on EC2'],
          correct: [1], explain: 'Event-driven, short-lived, zero server management: serverless functions.' },
        { kind: 'multi', prompt: 'Which pairs are matched correctly? (Pick 2)',
          options: ['EC2 → resizable virtual machines', 'S3 → object storage', 'RDS → DNS hosting', 'Lambda → block storage'],
          correct: [0, 1], explain: 'RDS is databases (Route 53 is DNS); Lambda is compute (EBS is block storage).' },
      ],
    }),
    t({
      id: 'clf-managed-vs-diy',
      title: 'Managed vs Do-It-Yourself',
      examDomain: CLF_DOMAIN.tech,
      summary: 'You CAN run your own database, queue, and mail server on EC2. Managed services trade that toil for an API — and shift patching, failover, and backups onto AWS.',
      primer: 'You can run almost anything yourself on EC2 — a database, a queue, a mail server. Managed services exist because most of that work is UNDIFFERENTIATED HEAVY LIFTING: patching, backups, failover, scaling plumbing that every company does identically and no customer ever notices. RDS versus self-managed MySQL is the canonical example: same engine, but AWS carries the 3 a.m. failover and the backup schedule. The trade is control for toil — you give up OS root access; you gain operations that don\'t depend on one human\'s vacation schedule. Choose DIY when you genuinely need OS-level control; choose managed to spend humans on differentiated work.',
      quiz: [
        { kind: 'single', prompt: 'Choosing RDS over self-managed MySQL on EC2 primarily buys you:',
          options: ['A faster CPU', 'AWS operating the database: patching, backups, failover', 'Free storage', 'Root access to the host'],
          correct: [1], explain: 'Managed services move operational burden across the responsibility line — you keep schema and queries, AWS keeps 3 a.m. pages.' },
        { kind: 'single', prompt: 'The trade-off of managed services is usually:',
          options: ['Lower durability', 'Less low-level control (no OS/root access) in exchange for less toil', 'No backups', 'They only run in one AZ'],
          correct: [1], explain: 'You give up the ability to tweak the OS; you gain a service that runs itself.' },
        { kind: 'single', prompt: '"Undifferentiated heavy lifting" refers to:',
          options: ['Your unique business logic', 'Work every company does identically — patching, backups, scaling plumbing', 'Marketing', 'Data science'],
          correct: [1], explain: 'Nobody chooses your product because you patch MySQL beautifully. Outsource the identical work, invest in the different work.' },
        { kind: 'multi', prompt: 'Which are managed services? (Pick 2)',
          options: ['Amazon RDS', 'Amazon SQS', 'MySQL you installed on EC2', 'A queue you wrote over Redis on EC2'],
          correct: [0, 1], explain: 'RDS and SQS are operated by AWS; the EC2 variants are yours to nurse.' },
      ],
    }),
    t({
      id: 'clf-pricing-models',
      title: 'Pricing Models',
      examDomain: CLF_DOMAIN.billing,
      summary: 'On-Demand for the unpredictable, Savings Plans/Reserved for the steady, Spot for the interruptible. Matching workload to model is most of the bill.',
      primer: 'Compute pricing has three shapes, matched to workload shapes. ON-DEMAND: full flexibility at the premium price — right for unpredictable or brand-new workloads until you learn their baseline. SAVINGS PLANS / RESERVED: commit to a steady baseline for 1-3 years and save up to ~72% — right for the API that\'s run flat for a year; wrong for guesses. SPOT: spare AWS capacity at the deepest discount, reclaimable on a ~2-minute warning — perfect for checkpointed, interruptible batch work; fatal for stateful singletons. And the fourth model everyone forgets: OFF. The cheapest instance is the idle one you stopped.',
      quiz: [
        { kind: 'single', prompt: 'A steady API that has run 24/7 for a year should move to:',
          options: ['On-Demand', 'A Savings Plan / Reserved commitment (up to ~72% off)', 'Spot', 'The free tier'],
          correct: [1], explain: 'Predictable baseline = commit and save. On-Demand premium is for uncertainty you no longer have.' },
        { kind: 'single', prompt: 'Spot Instances are ideal for:',
          options: ['The production database', 'Interruptible batch work that can stop and resume', 'Anything with a strict SLA', 'DNS'],
          correct: [1], explain: 'Spot is spare capacity at a deep discount that AWS can reclaim on short notice — perfect for fault-tolerant batch, fatal for stateful singletons.' },
        { kind: 'single', prompt: 'A brand-new experiment with unknown traffic should start on:',
          options: ['A 3-year Reserved commitment', 'On-Demand — pay the flexibility premium until the shape is known', 'Spot only', 'Dedicated Hosts'],
          correct: [1], explain: 'Commit AFTER you know the baseline. Committing to a guess is how savings plans become donations.' },
        { kind: 'multi', prompt: 'Which reduce cost without changing the workload\'s code? (Pick 2)',
          options: ['Savings Plans on the steady baseline', 'Spot for the batch tier', 'Doubling instance sizes', 'Printing the bill'],
          correct: [0, 1], explain: 'Purchasing models are code-free levers: commit the base, Spot the interruptible.' },
      ],
    }),
    t({
      id: 'clf-support-plans',
      title: 'Support Plans',
      examDomain: CLF_DOMAIN.billing,
      summary: 'Basic is docs and billing help. Developer buys guidance. Business buys 24/7 humans and a <1-hour response when production is down. Enterprise adds a named TAM.',
      primer: 'AWS support is a ladder, priced as a share of your spend. BASIC (free): documentation, billing support, service health, and core Trusted Advisor checks — no technical humans. DEVELOPER: business-hours technical guidance for development questions. BUSINESS: the first 24/7 rung — phone and chat, under-one-hour response for production-down cases, full Trusted Advisor. ENTERPRISE: adds a named Technical Account Manager (TAM) and concierge-level reviews for organizations that need one. Trusted Advisor itself is automated best-practice checks (open security groups, idle spend, missing MFA). Match the rung to the requirement — over-buying support wastes exactly like over-provisioning.',
      quiz: [
        { kind: 'single', prompt: 'Production is down and you need AWS on the phone 24/7 with a <1 hour response. The minimum plan is:',
          options: ['Basic', 'Developer', 'Business', 'Enterprise'],
          correct: [2], explain: 'Business is the first tier with 24/7 phone/chat and a 1-hour target for production-down cases.' },
        { kind: 'single', prompt: 'A Technical Account Manager (TAM) comes with:',
          options: ['Basic', 'Developer', 'Business', 'Enterprise'],
          correct: [3], explain: 'Enterprise includes a named TAM and concierge-level guidance — priced accordingly.' },
        { kind: 'single', prompt: 'The Basic plan includes:',
          options: ['1-hour production support', 'Account/billing support, documentation, and Trusted Advisor core checks', 'A TAM', 'On-site engineers'],
          correct: [1], explain: 'Basic is free and thin: billing questions, docs, health dashboard, and the core Trusted Advisor checks.' },
        { kind: 'single', prompt: 'Trusted Advisor is best described as:',
          options: ['A human consultant', 'Automated checks against cost, security, and reliability best practices', 'A deployment tool', 'A database'],
          correct: [1], explain: 'It scans your account for low-hanging fruit — open security groups, idle instances, missing MFA — more checks on higher plans.' },
      ],
    }),
  ],
};
