import type { Topic } from '@content';

/** CloudOps Engineer – Associate (formerly SysOps Administrator, SOA series).
 *  Domains at the classic official weights: Monitoring, Logging & Remediation 20 ·
 *  Reliability & Business Continuity 16 · Deployment, Provisioning & Automation 18 ·
 *  Security & Compliance 16 · Networking & Content Delivery 18 ·
 *  Cost & Performance Optimization 12. */

const t = (o: { id: string; title: string; examDomain: string; summary: string; quiz: Topic['quiz'] }): Topic =>
  ({ ...o, blocks: [], connections: [], stages: [] });

export const SOA_DOMAIN = {
  mon: 'Monitoring, Logging, and Remediation',
  rel: 'Reliability and Business Continuity',
  dep: 'Deployment, Provisioning, and Automation',
  sec: 'Security and Compliance (Ops)',
  net: 'Networking and Content Delivery (Ops)',
  cost: 'Cost and Performance Optimization',
};

export const SOA_COURSE: { title: string; topics: Topic[] } = {
  title: 'On-Call: CloudOps Badge (SysOps)',
  topics: [
    t({
      id: 'soa-alarm-fatigue',
      title: 'Alarms Worth Waking For',
      examDomain: SOA_DOMAIN.mon,
      summary: '200 alarms that cry wolf train humans to ignore the one that matters. Alarm on symptoms customers feel, use composite alarms, and page only on actionable signal.',
      quiz: [
        { kind: 'single', prompt: 'The team ignores all pages because 195 of 200 daily alarms are noise. The core fix is:',
          options: ['Louder pager sounds', 'Alarm on customer-facing symptoms with sane thresholds; page only on actionable signal', 'More alarms for coverage', 'Rotating who ignores them'],
          correct: [1], explain: 'Alert fatigue is a signal-to-noise problem. Fewer, better alarms tied to user impact restore trust in the pager.' },
        { kind: 'single', prompt: 'A composite CloudWatch alarm lets you:',
          options: ['Combine several alarms with AND/OR so you page once on real incidents, not per-metric', 'Alarm without metrics', 'Email invoices', 'Silence CloudTrail'],
          correct: [0], explain: 'Composite alarms gate the page: "error rate AND latency" beats two separate midnight texts about one incident.' },
        { kind: 'single', prompt: 'CPU at 85% on an autoscaled fleet serving normal latency should:',
          options: ['Page immediately', 'Not page — high utilization without user impact is efficiency, not an incident', 'Trigger failover', 'Reboot the fleet'],
          correct: [1], explain: 'Symptom-based alerting: page on what customers feel (errors, latency), record the rest on dashboards.' },
        { kind: 'multi', prompt: 'Good alarm hygiene includes: (Pick 2)',
          options: ['Every alarm has a documented action', 'Thresholds tuned to page only when true', 'One alarm per metric per host', 'Paging the whole company'],
          correct: [0, 1], explain: 'If there\'s no action, it\'s a dashboard line, not a page. Precision keeps the pager meaningful.' },
      ],
    }),
    t({
      id: 'soa-runbook-automation',
      title: 'Runbooks That Run Themselves',
      examDomain: SOA_DOMAIN.mon,
      summary: 'The disk fills every Tuesday and a human SSHes in to clear it. SSM Automation turns the wiki page into an executable runbook the alarm can trigger at 3 a.m. without you.',
      quiz: [
        { kind: 'single', prompt: 'A recurring, well-understood remediation (clear temp files, restart a service) should be:',
          options: ['A wiki page', 'An SSM Automation runbook triggered by the CloudWatch alarm', 'A calendar reminder', 'The new hire\'s job'],
          correct: [1], explain: 'Known-fix incidents are automation, not staffing. The alarm fires, the runbook runs, the human sleeps.' },
        { kind: 'single', prompt: 'SSM Run Command vs SSH-ing to each instance:',
          options: ['Identical', 'Run Command executes across the fleet with IAM auth and full audit logging — no keys, no open port 22', 'SSH is more auditable', 'Run Command needs public IPs'],
          correct: [1], explain: 'Fleet-wide execution through the agent: IAM-controlled, logged, no inbound access required.' },
        { kind: 'single', prompt: 'The main risk of manual remediation at 3 a.m. is:',
          options: ['It\'s too fast', 'Sleepy humans on production make typo-shaped outages, and the fix lives in one person\'s head', 'It\'s too well documented', 'IAM blocks it'],
          correct: [1], explain: 'Automation is consistency: the runbook does the same steps at 3 a.m. as at 3 p.m., and everyone can read them.' },
        { kind: 'multi', prompt: 'Good automation targets are: (Pick 2)',
          options: ['Deterministic fixes with clear triggers', 'Actions you\'ve done identically 10+ times', 'Novel incidents never seen before', 'Anything involving judgment about data loss'],
          correct: [0, 1], explain: 'Automate the repeatable; keep humans for the novel and the judgment calls.' },
      ],
    }),
    t({
      id: 'soa-restore-drill',
      title: 'Backups You Have Restored',
      examDomain: SOA_DOMAIN.rel,
      summary: 'A backup you have never restored is a hope, not a plan. Define RPO/RTO, then drill the restore until the numbers are real.',
      quiz: [
        { kind: 'single', prompt: 'RPO (Recovery Point Objective) answers:',
          options: ['How fast you recover', 'How much data you can afford to lose (time since last good copy)', 'How much backups cost', 'Who is on call'],
          correct: [1], explain: 'RPO is the data-loss window; RTO is the downtime window. Backup frequency serves RPO; restore speed serves RTO.' },
        { kind: 'single', prompt: 'The only way to know your real RTO is:',
          options: ['Reading the backup console', 'Actually restoring — a timed drill into a clean environment', 'Asking the vendor', 'Assuming an hour'],
          correct: [1], explain: 'Restore drills surface the surprises (missing IAM, forgotten configs, 6-hour copies) while they\'re cheap.' },
        { kind: 'single', prompt: 'Nightly snapshots with a 4-hour restore meet which requirement set?',
          options: ['RPO 1h / RTO 1h', 'RPO 24h / RTO 4h', 'RPO 0 / RTO 0', 'Neither RPO nor RTO'],
          correct: [1], explain: 'Worst case you lose a day of data (nightly) and are down four hours (restore time). Match the numbers to the business, not vice versa.' },
        { kind: 'multi', prompt: 'A restore drill should verify: (Pick 2)',
          options: ['The data is complete and consistent', 'The app actually runs against the restored copy', 'The backup file exists', 'The console has a green icon'],
          correct: [0, 1], explain: 'Existence is not restorability. The drill ends when the application serves traffic from restored data.' },
      ],
    }),
    t({
      id: 'soa-asg-health',
      title: 'Health Checks That Tell the Truth',
      examDomain: SOA_DOMAIN.rel,
      summary: 'An Auto Scaling group that trusts EC2 status checks will happily keep instances whose app is dead. ELB health checks ask the application itself — and grace periods stop replace-loops.',
      quiz: [
        { kind: 'single', prompt: 'Instances pass EC2 status checks but the app returns 500s. The ASG keeps them because:',
          options: ['It is broken', 'It uses EC2 health checks (is the VM up?) instead of ELB health checks (is the APP up?)', 'Health checks are optional', 'The ALB is down'],
          correct: [1], explain: 'EC2 checks test the hypervisor\'s view. ELB checks hit your health endpoint — switch the ASG to ELB type so app-dead means replaced.' },
        { kind: 'single', prompt: 'New instances get terminated 30 seconds after launch, looping forever. The likely cause:',
          options: ['Spot reclaims', 'Health-check grace period shorter than app boot time — they\'re judged before they finish starting', 'AZ failure', 'IAM'],
          correct: [1], explain: 'The grace period must cover boot + warmup. Judging a booting instance kills it mid-startup, and the loop repeats on its replacement.' },
        { kind: 'single', prompt: 'A good /health endpoint should:',
          options: ['Always return 200', 'Check the app\'s critical dependencies enough to mean "able to serve", cheaply', 'Run the full test suite per request', 'Be public to the internet'],
          correct: [1], explain: 'Meaningful but cheap: can I serve traffic? Deep dependency storms and always-200 lies are both failure modes.' },
        { kind: 'multi', prompt: 'Flapping (replace-loops) are commonly caused by: (Pick 2)',
          options: ['Grace period too short', 'Health endpoint failing on a slow dependency', 'Too many AZs', 'Instance names'],
          correct: [0, 1], explain: 'Impatient judgment and oversensitive endpoints both kill healthy-enough instances on a loop.' },
      ],
    }),
    t({
      id: 'soa-launch-templates',
      title: 'No More Pet Servers',
      examDomain: SOA_DOMAIN.dep,
      summary: 'The hand-tuned "special" server nobody dares reboot is an outage on a timer. Launch templates + instance refresh make servers cattle: rebuilt from spec, replaced without ceremony.',
      quiz: [
        { kind: 'single', prompt: 'A launch template is:',
          options: ['A monitoring rule', 'The versioned spec (AMI, size, user data, SGs) an ASG uses to stamp identical instances', 'A billing report', 'A CloudFront setting'],
          correct: [1], explain: 'The template IS the server definition — versioned, reviewable, repeatable.' },
        { kind: 'single', prompt: 'Rolling new configuration to a fleet with launch templates is done by:',
          options: ['SSH-ing to each instance', 'New template version + ASG instance refresh replacing instances gradually', 'Rebooting everything at once', 'Editing instances in the console'],
          correct: [1], explain: 'Instance refresh drains and replaces in batches — config changes become deploys, not surgeries.' },
        { kind: 'single', prompt: '"Pets vs cattle" means:',
          options: ['A zoning rule', 'Servers should be replaceable units rebuilt from spec, not hand-nursed individuals', 'Use smaller instances', 'Name servers after animals'],
          correct: [1], explain: 'If a server\'s loss is a crisis, its uniqueness is the defect. Cattle die and are replaced by the template.' },
        { kind: 'multi', prompt: 'Golden AMIs / baked images help because: (Pick 2)',
          options: ['Boot is faster (software pre-installed)', 'Every instance starts identical', 'They eliminate billing', 'They patch themselves'],
          correct: [0, 1], explain: 'Bake once, boot many: speed and consistency. Patching still needs a pipeline that re-bakes.' },
      ],
    }),
    t({
      id: 'soa-patch-fleet',
      title: 'Patching at Fleet Scale',
      examDomain: SOA_DOMAIN.sec,
      summary: 'A critical CVE lands. Patch Manager applies it across the fleet in maintenance windows with compliance reporting — no SSH loop, no forgotten box.',
      quiz: [
        { kind: 'single', prompt: 'Patching 200 instances for a critical CVE is best done with:',
          options: ['SSH and a for-loop over a hosts file', 'SSM Patch Manager: baselines, maintenance windows, compliance report', 'Terminating everything', 'Waiting for AWS to patch the guest OS'],
          correct: [1], explain: 'Patch Manager schedules, applies, and PROVES patching fleet-wide. The hosts file always misses a box; AWS never patches your guest OS.' },
        { kind: 'single', prompt: 'A patch baseline defines:',
          options: ['Instance prices', 'Which patches (severity, classification, age) are approved to install where', 'DNS records', 'IAM policies'],
          correct: [1], explain: 'Baselines are patch policy as configuration: critical security within 7 days, etc.' },
        { kind: 'single', prompt: 'The compliance view matters because:',
          options: ['It looks nice', 'It shows exactly which instances remain unpatched — the audit answer and the risk list', 'It reduces cost', 'It replaces alarms'],
          correct: [1], explain: '"Are we patched?" needs evidence per instance, not a feeling. Compliance reporting is that evidence.' },
        { kind: 'multi', prompt: 'Maintenance windows exist to: (Pick 2)',
          options: ['Patch during low-traffic periods', 'Control concurrency so the fleet never all reboots at once', 'Make patching optional', 'Hide patching from audit'],
          correct: [0, 1], explain: 'When and how many at a time — patching without a self-inflicted outage.' },
      ],
    }),
    t({
      id: 'soa-vpc-debug',
      title: 'The Networking Checklist',
      examDomain: SOA_DOMAIN.net,
      summary: '"The instance can\'t reach the internet" is always one of four things: route table, internet gateway, security group, or NACL. Check in order; guessing is slower.',
      quiz: [
        { kind: 'single', prompt: 'A private-subnet instance can\'t reach the internet. The FIRST thing to check:',
          options: ['Instance size', 'The subnet\'s route table — is there a 0.0.0.0/0 route to a NAT/IGW?', 'The AMI', 'CloudFront'],
          correct: [1], explain: 'No default route, no internet — everything else is irrelevant until the route exists.' },
        { kind: 'single', prompt: 'Security groups differ from NACLs in that SGs are:',
          options: ['Subnet-level and stateless', 'Instance-level and STATEFUL — return traffic is automatically allowed', 'Only for databases', 'Deny-based'],
          correct: [1], explain: 'SGs: stateful allow-lists on the instance. NACLs: stateless subnet filters that need BOTH directions (hello, ephemeral ports).' },
        { kind: 'single', prompt: 'Requests reach the instance but responses never return. Classic culprit:',
          options: ['A NACL missing the outbound ephemeral-port range (1024-65535)', 'The IGW is slow', 'DNS', 'The keyboard'],
          correct: [0], explain: 'Stateless NACLs must explicitly allow the return path. Forgetting ephemeral ports is the textbook one-way-traffic bug.' },
        { kind: 'multi', prompt: 'Useful tools for network debugging: (Pick 2)',
          options: ['VPC Reachability Analyzer', 'VPC Flow Logs', 'Cost Explorer', 'S3 inventory'],
          correct: [0, 1], explain: 'Reachability Analyzer walks the config path; Flow Logs show accepts/rejects that actually happened.' },
      ],
    }),
    t({
      id: 'soa-rightsize',
      title: 'Right-Sizing the Fleet',
      examDomain: SOA_DOMAIN.cost,
      summary: 'The fleet was sized by vibes in 2023 and runs at 4% CPU. Metrics-driven right-sizing and off-hours schedules cut the bill without touching a feature.',
      quiz: [
        { kind: 'single', prompt: 'A fleet averaging 4% CPU with flat memory for 90 days is:',
          options: ['Perfectly sized', 'Over-provisioned — right-size down against measured utilization', 'Under-provisioned', 'A security risk'],
          correct: [1], explain: 'Sustained single-digit utilization is money converted to idle heat. Compute Optimizer/CloudWatch data justifies smaller sizes.' },
        { kind: 'single', prompt: 'Dev/test environments used 9-to-5 weekdays should be:',
          options: ['Running 24/7 for readiness', 'Scheduled off outside working hours (~70% fewer instance-hours)', 'Moved to bigger instances', 'Made multi-region'],
          correct: [1], explain: '168 hours a week billed for 45 hours of use is the easiest savings in the account.' },
        { kind: 'single', prompt: 'Before shrinking production instances you should:',
          options: ['Just do it Friday evening', 'Check PEAK utilization and burst patterns, not averages, then step down with monitoring', 'Disable alarms', 'Ask the vendor'],
          correct: [1], explain: 'Averages hide peaks. Right-size against p99 usage with a rollback path, one step at a time.' },
        { kind: 'multi', prompt: 'Signals of over-provisioning include: (Pick 2)',
          options: ['Sustained low CPU AND low memory', 'Burst credits never consumed', 'High p99 latency', 'Full disks'],
          correct: [0, 1], explain: 'Both resources idle and burst headroom untouched = paying for capacity the workload never asks for.' },
      ],
    }),
  ],
};
